import { passage, spanishReading, frenchReading } from './data';
import { spanishA1Pilot } from './spanishA1Pilot';
import { spanishA1Batch2 } from './spanishA1Batch2';
import { spanishA1VocabReadings } from './spanishA1VocabReadings';

const splitSentences = text => text.match(/[^.!?]+[.!?]+/g)?.map(s=>s.trim()) || [text];

export const readingCurriculum = {
  English: [
    {id:'en-a1-cafe',level:'A1',unit:1,title:'A morning at the café',topic:'Daily life',description:'Order breakfast and follow a simple morning routine.',minutes:2,newWords:9,passage:'Every morning, Leo visits a small café near his home. He orders tea and bread with butter. The woman at the counter knows his name. Leo sits by the window and reads the news. At eight o’clock, he leaves for work.',sentences:splitSentences('Every morning, Leo visits a small café near his home. He orders tea and bread with butter. The woman at the counter knows his name. Leo sits by the window and reads the news. At eight o’clock, he leaves for work.'),sentenceTranslations:['Leo visits a nearby café each morning.','He asks for tea and buttered bread.','The server recognizes him.','He reads the news beside the window.','He goes to work at eight.'],practice:[{text:['Leo visits a small ',' near his home.'],answer:'café',choices:['station','café','school']},{text:['He sits by the ','.'],answer:'window',choices:['window','door','counter']},{text:['At eight, he leaves for ','.'],answer:'work',choices:['lunch','home','work']}]},
    {id:'en-a2-brighton',level:'A2',unit:2,title:'A quiet day by the sea',topic:'Travel',description:'Follow a short train journey from London to Brighton.',minutes:3,newWords:12,passage,sentences:splitSentences(passage),sentenceTranslations:['Maya travels to Brighton early on Saturday.','She wants a peaceful day away from London.','She watches the countryside from the train.','Brighton feels fresh and the beach is quiet.','She reads a saved book near the pier.'],practice:[{text:['Maya ',' the early train.'],answer:'took',choices:['taked','took','taken']},{text:['The beach was almost ','.'],answer:'empty',choices:['empty','noisy','late']},{text:['She found a bench near the ','.'],answer:'pier',choices:['village','window','pier']}]},
    {id:'en-b1-first-day',level:'B1',unit:3,title:'The first day at a new job',topic:'Work',description:'Understand feelings and events in a professional setting.',minutes:4,newWords:15,passage:'Nora felt nervous before her first day at the design studio. Her manager introduced her to the team and showed her around the office. Although there was a lot to remember, everyone answered her questions patiently. By lunchtime, Nora had already joined a small project meeting. She returned home tired but excited about the week ahead.',sentences:splitSentences('Nora felt nervous before her first day at the design studio. Her manager introduced her to the team and showed her around the office. Although there was a lot to remember, everyone answered her questions patiently. By lunchtime, Nora had already joined a small project meeting. She returned home tired but excited about the week ahead.'),sentenceTranslations:['Nora was anxious before starting her new job.','Her manager helped her meet the team and learn the office.','Her colleagues patiently helped with her questions.','She attended a project meeting before lunch ended.','She felt tired and optimistic when she went home.'],practice:[{text:['Nora felt ',' before her first day.'],answer:'nervous',choices:['nervous','angry','bored']},{text:['Her manager introduced her to the ','.'],answer:'team',choices:['train','team','family']},{text:['She returned home tired but ','.'],answer:'excited',choices:['empty','excited','quiet']}]},
    {id:'en-b2-city',level:'B2',unit:4,title:'Rethinking city life',topic:'Society',description:'Explore an argument about sustainable urban spaces.',minutes:6,newWords:20,locked:true},
    {id:'en-c1-ideas',level:'C1',unit:5,title:'How ideas change',topic:'Academic',description:'Analyze a nuanced text about knowledge and innovation.',minutes:8,newWords:24,locked:true}
  ],
  Spanish: [
    ...spanishA1Pilot,
    ...spanishA1Batch2,
    ...spanishA1VocabReadings,
    {id:'es-a1-valencia',level:'A1',unit:1,sentenceAudioPrefix:'/audio/spanish/reading-sentence-',description:'Acompaña a Ana en un día tranquilo junto al mar.',minutes:2,newWords:16,...spanishReading,practice:[{text:['Ana ',' el tren a Valencia.'],answer:'toma',choices:['toma','tomas','tomar']},{text:['La playa está casi ','.'],answer:'vacía',choices:['fría','pequeña','vacía']},{text:['Ana encuentra un banco junto al ','.'],answer:'puerto',choices:['puerto','tren','libro']}]},
    {id:'es-a1-mercado',level:'A1',unit:2,title:'El mercado del barrio',topic:'Vida diaria',description:'Compra alimentos y habla con vendedores en el mercado.',minutes:3,newWords:13,audio:'/audio/spanish/reading-mercado.mp3',passage:'Los martes, Elena va al mercado de su barrio. Lleva una bolsa grande y una lista corta. Primero compra tomates, pan y queso. Después habla con el vendedor de frutas y elige unas manzanas rojas. Antes de volver a casa, toma un café en la plaza.',sentences:splitSentences('Los martes, Elena va al mercado de su barrio. Lleva una bolsa grande y una lista corta. Primero compra tomates, pan y queso. Después habla con el vendedor de frutas y elige unas manzanas rojas. Antes de volver a casa, toma un café en la plaza.'),sentenceTranslations:['On Tuesdays, Elena goes to her neighborhood market.','She carries a large bag and a short list.','First, she buys tomatoes, bread, and cheese.','Then she talks to the fruit seller and chooses some red apples.','Before going home, she has a coffee in the square.'],practice:[{text:['Elena va al ',' de su barrio.'],answer:'mercado',choices:['mercado','puerto','tren']},{text:['Compra tomates, pan y ','.'],answer:'queso',choices:['café','queso','frutas']},{text:['Toma un café en la ','.'],answer:'plaza',choices:['bolsa','plaza','lista']}]},
    {id:'es-a2-excursion',level:'A2',unit:3,title:'Una excursión inesperada',topic:'Naturaleza',description:'Descubre cómo cambia un viaje cuando empieza a llover.',minutes:4,newWords:17,audio:'/audio/spanish/reading-excursion.mp3',passage:'Pablo y sus amigos planean una excursión a la montaña. Por la mañana, el cielo está claro, pero el tiempo cambia rápidamente. Cuando empieza a llover, encuentran una pequeña cabaña cerca del camino. Allí comparten la comida y esperan juntos. Al final, la lluvia termina y regresan al pueblo riéndose.',sentences:splitSentences('Pablo y sus amigos planean una excursión a la montaña. Por la mañana, el cielo está claro, pero el tiempo cambia rápidamente. Cuando empieza a llover, encuentran una pequeña cabaña cerca del camino. Allí comparten la comida y esperan juntos. Al final, la lluvia termina y regresan al pueblo riéndose.'),sentenceTranslations:['Pablo and his friends plan a trip to the mountains.','The morning is clear, but the weather changes quickly.','When it starts raining, they find a small cabin near the path.','They share their food and wait together there.','The rain eventually stops and they return to the village laughing.'],practice:[{text:['Planean una excursión a la ','.'],answer:'montaña',choices:['montaña','ventana','plaza']},{text:['Encuentran una pequeña ','.'],answer:'cabaña',choices:['bolsa','cabaña','playa']},{text:['Regresan al pueblo ','.'],answer:'riéndose',choices:['lloviendo','riéndose','comprando']}]},
    {id:'es-b1-work',level:'B1',unit:4,title:'El primer día de trabajo',topic:'Trabajo',description:'Sigue una experiencia profesional y nuevas relaciones.',minutes:5,newWords:20,locked:true},
    {id:'es-b2-city',level:'B2',unit:5,title:'Repensar la vida urbana',topic:'Sociedad',description:'Analiza ideas sobre ciudades sostenibles.',minutes:7,newWords:24,locked:true}
  ],
  French: [
    {id:'fr-a1-nice',level:'A1',unit:1,sentenceAudioPrefix:'/audio/french/reading-sentence-',description:'Suivez Camille pendant une journée calme au bord de la mer.',minutes:2,newWords:16,...frenchReading,practice:[{text:['Camille ',' le train pour Nice.'],answer:'prend',choices:['prend','prendre','prends']},{text:['La plage est presque ','.'],answer:'vide',choices:['fraîche','petite','vide']},{text:['Camille trouve un banc près du ','.'],answer:'port',choices:['port','train','livre']}]},
    {id:'fr-a1-marche',level:'A1',unit:2,title:'Au marché du quartier',topic:'Vie quotidienne',description:'Achetez des aliments et parlez avec les commerçants.',minutes:3,newWords:13,audio:'/audio/french/reading-marche.mp3',passage:'Le mardi, Élodie va au marché de son quartier. Elle porte un grand sac et une petite liste. D’abord, elle achète des tomates, du pain et du fromage. Ensuite, elle parle avec le marchand de fruits et choisit des pommes rouges. Avant de rentrer, elle prend un café sur la place.',sentences:splitSentences('Le mardi, Élodie va au marché de son quartier. Elle porte un grand sac et une petite liste. D’abord, elle achète des tomates, du pain et du fromage. Ensuite, elle parle avec le marchand de fruits et choisit des pommes rouges. Avant de rentrer, elle prend un café sur la place.'),sentenceTranslations:['On Tuesdays, Élodie goes to her neighborhood market.','She carries a large bag and a short list.','First, she buys tomatoes, bread, and cheese.','Then she talks with the fruit seller and chooses red apples.','Before going home, she has a coffee in the square.'],practice:[{text:['Élodie va au ',' de son quartier.'],answer:'marché',choices:['marché','port','train']},{text:['Elle achète du pain et du ','.'],answer:'fromage',choices:['café','fromage','fruit']},{text:['Elle prend un café sur la ','.'],answer:'place',choices:['liste','place','route']}]},
    {id:'fr-a2-excursion',level:'A2',unit:3,title:'Une excursion imprévue',topic:'Nature',description:'Découvrez comment un voyage change avec la météo.',minutes:4,newWords:17,audio:'/audio/french/reading-excursion.mp3',passage:'Paul et ses amis préparent une excursion à la montagne. Le matin, le ciel est clair, mais le temps change rapidement. Quand il commence à pleuvoir, ils trouvent une petite cabane près du chemin. Ils partagent leur repas et attendent ensemble. Enfin, la pluie s’arrête et ils rentrent au village en riant.',sentences:splitSentences('Paul et ses amis préparent une excursion à la montagne. Le matin, le ciel est clair, mais le temps change rapidement. Quand il commence à pleuvoir, ils trouvent une petite cabane près du chemin. Ils partagent leur repas et attendent ensemble. Enfin, la pluie s’arrête et ils rentrent au village en riant.'),sentenceTranslations:['Paul and his friends prepare a trip to the mountains.','The sky is clear in the morning, but the weather changes quickly.','When it starts to rain, they find a small cabin near the path.','They share their meal and wait together.','Finally, the rain stops and they return to the village laughing.'],practice:[{text:['Ils préparent une excursion à la ','.'],answer:'montagne',choices:['montagne','fenêtre','place']},{text:['Ils trouvent une petite ','.'],answer:'cabane',choices:['plage','cabane','boisson']},{text:['Ils rentrent au village en ','.'],answer:'riant',choices:['riant','achetant','pleuvant']}]},
    {id:'fr-b1-work',level:'B1',unit:4,title:'Le premier jour au travail',topic:'Travail',description:'Suivez une nouvelle expérience professionnelle.',minutes:5,newWords:20,locked:true},
    {id:'fr-b2-city',level:'B2',unit:5,title:'Repenser la vie urbaine',topic:'Société',description:'Analysez des idées sur les villes durables.',minutes:7,newWords:24,locked:true}
  ]
};

export const levelMeta={A1:{label:'Beginner',color:'#2BAE7A'},A2:{label:'Elementary',color:'#13599B'},B1:{label:'Intermediate',color:'#7A5AF8'},B2:{label:'Upper intermediate',color:'#F5A623'},C1:{label:'Advanced',color:'#E1526A'}};
