import React, { useState } from 'react';
import { AlignJustify, Check, Eye, Focus, Palette, RotateCcw, Settings2, Type, X } from 'lucide-react';

export const defaultReadingSettings={fontSize:'medium',lineSpacing:'comfortable',textWidth:'standard',sentenceMode:false,showTranslations:false,showGender:true,syncHighlight:true,dyslexiaFont:false,focusMode:false};

const Choice=({active,onClick,children})=><button onClick={onClick} className={`rounded-lg border px-3 py-2 text-xs font-extrabold transition ${active?'border-brand bg-blue-50 text-brand':'border-slate-200 bg-white text-slate-500 hover:border-brand'}`}>{children}</button>;
const Toggle=({checked,onChange,label,description})=><button onClick={()=>onChange(!checked)} className="flex w-full items-center justify-between gap-4 rounded-xl py-2.5 text-left"><span><span className="block text-sm font-extrabold">{label}</span><span className="mt-0.5 block text-xs text-slate-500">{description}</span></span><span className={`relative h-6 w-11 shrink-0 rounded-full transition ${checked?'bg-brand':'bg-slate-300'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition ${checked?'left-6':'left-1'}`}/></span></button>;

export default function ReadingControls({settings,onChange}){
 const [open,setOpen]=useState(false);const update=(key,value)=>onChange({...settings,[key]:value});const reset=()=>onChange({...defaultReadingSettings});
 return <div className="relative"><button onClick={()=>setOpen(!open)} className="btn-secondary !py-2 text-sm" aria-expanded={open}><Settings2 size={17}/>Reading settings</button>{open&&<><button className="fixed inset-0 z-30 cursor-default bg-transparent" onClick={()=>setOpen(false)} aria-label="Close reading settings"/><div className="absolute right-0 z-40 mt-2 w-[min(92vw,390px)] rounded-2xl border border-slate-200 bg-white p-5 shadow-soft"><div className="flex items-center justify-between"><div><div className="flex items-center gap-2 font-black"><Settings2 size={18} className="text-brand"/>Reading settings</div><p className="mt-1 text-xs text-slate-500">Adjust the page for comfortable reading.</p></div><button onClick={()=>setOpen(false)} className="grid h-8 w-8 place-items-center rounded-full hover:bg-surface"><X size={17}/></button></div>
 <div className="mt-5 space-y-5"><div><div className="mb-2 flex items-center gap-2 text-xs font-extrabold uppercase tracking-wider text-slate-400"><Type size={15}/>Text size</div><div className="grid grid-cols-3 gap-2"><Choice active={settings.fontSize==='small'} onClick={()=>update('fontSize','small')}>Small</Choice><Choice active={settings.fontSize==='medium'} onClick={()=>update('fontSize','medium')}>Medium</Choice><Choice active={settings.fontSize==='large'} onClick={()=>update('fontSize','large')}>Large</Choice></div></div>
 <div><div className="mb-2 flex items-center gap-2 text-xs font-extrabold uppercase tracking-wider text-slate-400"><AlignJustify size={15}/>Line spacing</div><div className="grid grid-cols-3 gap-2"><Choice active={settings.lineSpacing==='compact'} onClick={()=>update('lineSpacing','compact')}>Compact</Choice><Choice active={settings.lineSpacing==='comfortable'} onClick={()=>update('lineSpacing','comfortable')}>Comfort</Choice><Choice active={settings.lineSpacing==='relaxed'} onClick={()=>update('lineSpacing','relaxed')}>Relaxed</Choice></div></div>
 <div><div className="mb-2 text-xs font-extrabold uppercase tracking-wider text-slate-400">Reading width</div><div className="grid grid-cols-3 gap-2"><Choice active={settings.textWidth==='narrow'} onClick={()=>update('textWidth','narrow')}>Narrow</Choice><Choice active={settings.textWidth==='standard'} onClick={()=>update('textWidth','standard')}>Standard</Choice><Choice active={settings.textWidth==='wide'} onClick={()=>update('textWidth','wide')}>Wide</Choice></div></div>
 <div className="divide-y divide-slate-100 border-y border-slate-100 py-1"><Toggle checked={settings.sentenceMode} onChange={v=>update('sentenceMode',v)} label="Sentence-by-sentence" description="Place each sentence on its own line."/><Toggle checked={settings.showTranslations} onChange={v=>update('showTranslations',v)} label="Show translations" description="Display English below each sentence."/><Toggle checked={settings.showGender} onChange={v=>update('showGender',v)} label="Article gender colors" description="Blue masculine and red feminine articles."/><Toggle checked={settings.syncHighlight} onChange={v=>update('syncHighlight',v)} label="Audio-follow highlighting" description="Follow the active sentence and word."/><Toggle checked={settings.dyslexiaFont} onChange={v=>update('dyslexiaFont',v)} label="Readable letter shapes" description="Use wider spacing and distinct characters."/><Toggle checked={settings.focusMode} onChange={v=>update('focusMode',v)} label="Focus mode" description="Hide supporting panels while reading."/></div>
 <button onClick={reset} className="flex w-full items-center justify-center gap-2 rounded-xl py-2 text-sm font-extrabold text-slate-500 hover:bg-surface"><RotateCcw size={16}/>Reset defaults</button></div></div></>}</div>
}
