const vocab=items=>items.map(([word,translation,role='word in context'])=>({word,translation,role}));

export const spanishA1Pilot=[
{
 id:'es-a1-pilot-01',level:'A1',unit:1,title:'El primer día de Lucía',topic:'Presentaciones',description:'Lucía llega a un instituto nuevo y conoce a sus compañeros.',minutes:2,newWords:20,audio:'/audio/spanish/a1-pilot-01.mp3',
 grammarTargets:['Subject pronouns: yo, tú, él, ella','Ser in the present tense','Llamarse for names','Definite and indefinite articles'],
 targetVocabulary:['hola','adiós','nombre','chico','chica','estudiante','profesor','clase','instituto','nuevo','español','inglés','ciudad','país','vivir','ser','llamarse','amigo','compañero','también'],recycledVocabulary:[],
 passage:'Lucía es una estudiante nueva en un instituto de Madrid. Vive en la ciudad, pero su familia es de otro país. Al entrar en clase, un chico dice: «Hola, me llamo Pablo. ¿Cuál es tu nombre?». Lucía responde: «Me llamo Lucía. Soy española y también hablo inglés». Pablo es su nuevo compañero. La profesora entra y saluda a todos. Se llama Marta y es profesora de español. En la pausa, Lucía conoce a otra chica, Sara. Sara vive cerca del instituto y es amiga de Pablo. Los tres hablan de la clase y de la ciudad. Al final del día, Lucía dice adiós. Está contenta porque ya tiene dos amigos.',
 sentences:['Lucía es una estudiante nueva en un instituto de Madrid.','Vive en la ciudad, pero su familia es de otro país.','Al entrar en clase, un chico dice: «Hola, me llamo Pablo. ¿Cuál es tu nombre?».','Lucía responde: «Me llamo Lucía. Soy española y también hablo inglés».','Pablo es su nuevo compañero.','La profesora entra y saluda a todos.','Se llama Marta y es profesora de español.','En la pausa, Lucía conoce a otra chica, Sara.','Sara vive cerca del instituto y es amiga de Pablo.','Los tres hablan de la clase y de la ciudad.','Al final del día, Lucía dice adiós.','Está contenta porque ya tiene dos amigos.'],
 sentenceTranslations:['Lucía is a new student at a school in Madrid.','She lives in the city, but her family is from another country.','When she enters the classroom, a boy says, “Hello, my name is Pablo. What is your name?”','Lucía answers, “My name is Lucía. I am Spanish and I also speak English.”','Pablo is her new classmate.','The teacher enters and greets everyone.','Her name is Marta and she is a Spanish teacher.','During the break, Lucía meets another girl, Sara.','Sara lives near the school and is Pablo’s friend.','The three of them talk about the class and the city.','At the end of the day, Lucía says goodbye.','She is happy because she already has two friends.'],
 customVocabulary:vocab([['hola','hello','greeting'],['adiós','goodbye','greeting'],['nombre','name','noun'],['chico','boy','noun'],['chica','girl','noun'],['estudiante','student','noun'],['profesor','teacher','noun'],['clase','class / classroom','noun'],['instituto','secondary school','noun'],['nuevo','new','adjective'],['español','Spanish','adjective / noun'],['inglés','English','adjective / noun'],['ciudad','city','noun'],['país','country','noun'],['vivir','to live','verb'],['ser','to be','verb'],['llamarse','to be called','reflexive verb'],['amigo','friend','noun'],['compañero','classmate','noun'],['también','also','adverb']]),
 comprehension:[{type:'Main idea',prompt:'Why is the day important for Lucía?',choices:['It is her first day at a new school.','She is travelling to another country.','She is visiting her grandmother.'],answer:'It is her first day at a new school.',feedback:'Lucía is a new student at an institute in Madrid.'},{type:'Detail',prompt:'What languages does Lucía mention?',choices:['Spanish and English','Spanish and French','English and French'],answer:'Spanish and English',feedback:'She says that she is Spanish and also speaks English.'},{type:'Inference',prompt:'How does Lucía feel at the end?',choices:['Happy','Angry','Bored'],answer:'Happy',feedback:'She is happy because she has already made two friends.'}],
 practice:[{text:['Lucía ',' una estudiante nueva.'],answer:'es',choices:['es','soy','eres']},{text:['Yo me ',' Lucía.'],answer:'llamo',choices:['llamas','llamo','llama']},{text:['Pablo es su nuevo ','.'],answer:'compañero',choices:['país','compañero','nombre']}]
},
{
 id:'es-a1-pilot-02',level:'A1',unit:2,title:'Una tarde con la familia',topic:'Familia y hogar',description:'Pablo presenta a su familia y sus mascotas a Lucía.',minutes:2,newWords:20,audio:'/audio/spanish/a1-pilot-02.mp3',
 grammarTargets:['Tener in the present tense','Possessive adjectives','Noun gender and number','Adjective agreement'],
 targetVocabulary:['familia','madre','padre','hermano','hermana','abuelo','abuela','casa','mascota','perro','gato','pequeño','grande','joven','tener','mi','tu','su','nuestro','juntos'],recycledVocabulary:['amigo','chica','compañero','vivir','ciudad'],
 passage:'Después de clase, Lucía va a casa de su amigo Pablo. Su casa es grande y está cerca del instituto. Pablo presenta a su familia. Su madre se llama Elena y su padre se llama Carlos. Tiene un hermano pequeño, Mateo, y una hermana joven, Sofía. Su abuelo y su abuela viven en otra ciudad, pero vienen algunos domingos. La familia también tiene dos mascotas. Su perro se llama Coco y su gato se llama Nube. Coco es grande y muy activo; Nube es pequeña y tranquila. Pablo pregunta: «¿Tu familia tiene mascotas?». Lucía responde: «En mi casa tenemos un perro pequeño. Es nuestra mascota». Todos toman una merienda juntos. Lucía piensa que la familia de Pablo es muy simpática.',
 sentences:['Después de clase, Lucía va a casa de su amigo Pablo.','Su casa es grande y está cerca del instituto.','Pablo presenta a su familia.','Su madre se llama Elena y su padre se llama Carlos.','Tiene un hermano pequeño, Mateo, y una hermana joven, Sofía.','Su abuelo y su abuela viven en otra ciudad, pero vienen algunos domingos.','La familia también tiene dos mascotas.','Su perro se llama Coco y su gato se llama Nube.','Coco es grande y muy activo; Nube es pequeña y tranquila.','Pablo pregunta: «¿Tu familia tiene mascotas?».','Lucía responde: «En mi casa tenemos un perro pequeño. Es nuestra mascota».','Todos toman una merienda juntos.','Lucía piensa que la familia de Pablo es muy simpática.'],
 sentenceTranslations:['After class, Lucía goes to her friend Pablo’s house.','His house is large and is near the school.','Pablo introduces his family.','His mother’s name is Elena and his father’s name is Carlos.','He has a little brother, Mateo, and a young sister, Sofía.','His grandfather and grandmother live in another city, but they come on some Sundays.','The family also has two pets.','Their dog is called Coco and their cat is called Nube.','Coco is big and very active; Nube is small and calm.','Pablo asks, “Does your family have pets?”','Lucía answers, “We have a small dog at my house. It is our pet.”','Everyone has an afternoon snack together.','Lucía thinks Pablo’s family is very nice.'],
 customVocabulary:vocab([['familia','family','noun'],['madre','mother','noun'],['padre','father','noun'],['hermano','brother','noun'],['hermana','sister','noun'],['abuelo','grandfather','noun'],['abuela','grandmother','noun'],['casa','house / home','noun'],['mascota','pet','noun'],['perro','dog','noun'],['gato','cat','noun'],['pequeño','small','adjective'],['grande','big / large','adjective'],['joven','young','adjective'],['tener','to have','verb'],['mi','my','possessive adjective'],['tu','your','possessive adjective'],['su','his / her / their','possessive adjective'],['nuestro','our','possessive adjective'],['juntos','together','adverb']]),
 comprehension:[{type:'Detail',prompt:'Where does Lucía go after class?',choices:['To Pablo’s house','To the library','To her grandmother’s house'],answer:'To Pablo’s house',feedback:'She goes to the house of her friend Pablo.'},{type:'Detail',prompt:'How many pets does Pablo’s family have?',choices:['One','Two','Three'],answer:'Two',feedback:'The family has a dog called Coco and a cat called Nube.'},{type:'Meaning',prompt:'What does Lucía think about Pablo’s family?',choices:['They are very nice.','They are very quiet.','They are very small.'],answer:'They are very nice.',feedback:'The final sentence says that the family is very nice.'}],
 practice:[{text:['Pablo ',' un hermano pequeño.'],answer:'tiene',choices:['tengo','tiene','tienes']},{text:['Coco es su ','.'],answer:'perro',choices:['gato','perro','abuelo']},{text:['Es ',' mascota.'],answer:'nuestra',choices:['nuestro','nuestra','nuestros']}]
},
{
 id:'es-a1-pilot-03',level:'A1',unit:3,title:'La rutina de Sara',topic:'Rutinas y tiempo',description:'Sara cuenta cómo es un día normal de instituto.',minutes:2,newWords:20,audio:'/audio/spanish/a1-pilot-03.mp3',
 grammarTargets:['Regular present-tense verbs','Common reflexive verbs','Telling time','Sequencing adverbs'],
 targetVocabulary:['mañana','noche','despertarse','levantarse','desayunar','comer','cenar','ir','estudiar','volver','dormir','siempre','normalmente','primero','después','temprano','tarde','hora','empezar','terminar'],recycledVocabulary:['instituto','clase','casa','amigo','familia'],
 passage:'Sara se despierta temprano de lunes a viernes. Normalmente se levanta a las siete de la mañana. Primero se ducha y después desayuna leche, pan y fruta. A las ocho va al instituto con su amigo Pablo. Las clases empiezan a las ocho y media y terminan a las dos. Sara estudia inglés, ciencias y música. A la hora de comer, vuelve a casa y come con su madre. Por la tarde hace los deberes y habla con Lucía por teléfono. Después escucha música o lee un libro. Su familia cena a las nueve de la noche. Sara siempre prepara su mochila antes de dormir. Normalmente duerme ocho horas. Los sábados no se levanta temprano porque no tiene clase.',
 sentences:['Sara se despierta temprano de lunes a viernes.','Normalmente se levanta a las siete de la mañana.','Primero se ducha y después desayuna leche, pan y fruta.','A las ocho va al instituto con su amigo Pablo.','Las clases empiezan a las ocho y media y terminan a las dos.','Sara estudia inglés, ciencias y música.','A la hora de comer, vuelve a casa y come con su madre.','Por la tarde hace los deberes y habla con Lucía por teléfono.','Después escucha música o lee un libro.','Su familia cena a las nueve de la noche.','Sara siempre prepara su mochila antes de dormir.','Normalmente duerme ocho horas.','Los sábados no se levanta temprano porque no tiene clase.'],
 sentenceTranslations:['Sara wakes up early from Monday to Friday.','She normally gets up at seven in the morning.','First she takes a shower and then has milk, bread, and fruit for breakfast.','At eight she goes to school with her friend Pablo.','Classes start at eight thirty and finish at two.','Sara studies English, science, and music.','At lunchtime, she returns home and eats with her mother.','In the afternoon, she does her homework and talks to Lucía on the phone.','Afterwards, she listens to music or reads a book.','Her family has dinner at nine at night.','Sara always prepares her backpack before sleeping.','She normally sleeps for eight hours.','On Saturdays, she does not get up early because she has no class.'],
 customVocabulary:vocab([['mañana','morning','noun'],['noche','night','noun'],['despertarse','to wake up','reflexive verb'],['levantarse','to get up','reflexive verb'],['desayunar','to have breakfast','verb'],['comer','to eat / have lunch','verb'],['cenar','to have dinner','verb'],['ir','to go','verb'],['estudiar','to study','verb'],['volver','to return','verb'],['dormir','to sleep','verb'],['siempre','always','adverb'],['normalmente','normally','adverb'],['primero','first','sequencing adverb'],['después','afterwards','sequencing adverb'],['temprano','early','adverb'],['tarde','afternoon / late','noun / adverb'],['hora','hour / time','noun'],['empezar','to begin','verb'],['terminar','to finish','verb']]),
 comprehension:[{type:'Sequence',prompt:'What does Sara do after getting up?',choices:['She has breakfast.','She goes to bed.','She has dinner.'],answer:'She has breakfast.',feedback:'First she showers and then she has breakfast.'},{type:'Detail',prompt:'What time do classes finish?',choices:['At two','At eight','At nine'],answer:'At two',feedback:'The classes start at 8:30 and finish at 2:00.'},{type:'Inference',prompt:'Why does Sara get up later on Saturdays?',choices:['She has no class.','She studies English.','She visits Pablo.'],answer:'She has no class.',feedback:'The text directly connects sleeping later with not having class.'}],
 practice:[{text:['Sara se ',' a las siete.'],answer:'levanta',choices:['levanto','levanta','levantamos']},{text:['Las clases ',' a las ocho y media.'],answer:'empiezan',choices:['empieza','empiezan','empezamos']},{text:['Sara ',' estudia por la tarde.'],answer:'normalmente',choices:['noche','hora','normalmente']}]
},
{
 id:'es-a1-pilot-04',level:'A1',unit:4,title:'¿Dónde está mi cuaderno?',topic:'El instituto',description:'Lucía busca su cuaderno mientras aprende a describir lugares.',minutes:2,newWords:20,audio:'/audio/spanish/a1-pilot-04.mp3',
 grammarTargets:['Hay for existence','Estar for location','Prepositions of place','Question word dónde'],
 targetVocabulary:['aula','mesa','silla','puerta','ventana','libro','cuaderno','mochila','lápiz','ordenador','pizarra','biblioteca','gimnasio','patio','haber','estar','delante','detrás','cerca','lejos'],recycledVocabulary:['clase','profesora','instituto','estudiar','compañero'],
 passage:'La clase de Lucía empieza pronto, pero ella no encuentra su cuaderno. Mira dentro de la mochila. Hay un libro y un lápiz, pero el cuaderno no está allí. En el aula hay muchas mesas y sillas. El ordenador de la profesora está delante de la pizarra. Lucía mira detrás de su silla y cerca de la ventana. Después pregunta a Pablo: «¿Dónde está mi cuaderno?». Pablo recuerda que estudiaron juntos en la biblioteca. La biblioteca está lejos del aula de música, pero cerca del gimnasio. Los dos salen por la puerta y cruzan el patio. En la biblioteca, el cuaderno está sobre una mesa, detrás de dos libros. Lucía sonríe y vuelve al aula antes de la clase.',
 sentences:['La clase de Lucía empieza pronto, pero ella no encuentra su cuaderno.','Mira dentro de la mochila.','Hay un libro y un lápiz, pero el cuaderno no está allí.','En el aula hay muchas mesas y sillas.','El ordenador de la profesora está delante de la pizarra.','Lucía mira detrás de su silla y cerca de la ventana.','Después pregunta a Pablo: «¿Dónde está mi cuaderno?».','Pablo recuerda que estudiaron juntos en la biblioteca.','La biblioteca está lejos del aula de música, pero cerca del gimnasio.','Los dos salen por la puerta y cruzan el patio.','En la biblioteca, el cuaderno está sobre una mesa, detrás de dos libros.','Lucía sonríe y vuelve al aula antes de la clase.'],
 sentenceTranslations:['Lucía’s class starts soon, but she cannot find her notebook.','She looks inside her backpack.','There is a book and a pencil, but the notebook is not there.','There are many tables and chairs in the classroom.','The teacher’s computer is in front of the board.','Lucía looks behind her chair and near the window.','Then she asks Pablo, “Where is my notebook?”','Pablo remembers that they studied together in the library.','The library is far from the music room but near the gym.','The two of them go out through the door and cross the playground.','In the library, the notebook is on a table, behind two books.','Lucía smiles and returns to the classroom before class.'],
 customVocabulary:vocab([['aula','classroom','noun'],['mesa','table / desk','noun'],['silla','chair','noun'],['puerta','door','noun'],['ventana','window','noun'],['libro','book','noun'],['cuaderno','notebook','noun'],['mochila','backpack','noun'],['lápiz','pencil','noun'],['ordenador','computer','noun'],['pizarra','board','noun'],['biblioteca','library','noun'],['gimnasio','gym','noun'],['patio','playground / courtyard','noun'],['haber','to exist; used as hay','verb'],['estar','to be / be located','verb'],['delante','in front','preposition / adverb'],['detrás','behind','preposition / adverb'],['cerca','near','preposition / adverb'],['lejos','far','adverb']]),
 comprehension:[{type:'Main idea',prompt:'What is Lucía looking for?',choices:['Her notebook','Her computer','Her backpack'],answer:'Her notebook',feedback:'She cannot find her notebook before class.'},{type:'Detail',prompt:'Where is the notebook?',choices:['On a table in the library','Behind a chair in the classroom','Near the gym'],answer:'On a table in the library',feedback:'They find it on a library table behind two books.'},{type:'Location',prompt:'What is near the gym?',choices:['The library','The playground','The window'],answer:'The library',feedback:'The library is described as being near the gym.'}],
 practice:[{text:['En el aula ',' muchas mesas.'],answer:'hay',choices:['es','hay','tiene']},{text:['El ordenador está ',' de la pizarra.'],answer:'delante',choices:['delante','lejos','dentro']},{text:['¿Dónde ',' mi cuaderno?'],answer:'está',choices:['es','está','hay']}]
},
{
 id:'es-a1-pilot-05',level:'A1',unit:5,title:'Un plan en la cafetería',topic:'Comida y compras',description:'Los amigos piden una merienda y hacen un plan para el sábado.',minutes:2,newWords:20,audio:'/audio/spanish/a1-pilot-05.mp3',
 grammarTargets:['Querer and gustar','Question words qué, cuál and cuánto','Polite requests with querer','Connectors porque and pero'],
 targetVocabulary:['cafetería','bocadillo','agua','zumo','fruta','precio','euro','pedir','querer','gustar','comprar','pagar','cuánto','qué','cuál','porque','pero','barato','caro','hambre'],recycledVocabulary:['amigo','instituto','juntos','después','tarde'],
 passage:'El viernes por la tarde, Lucía, Pablo y Sara van a la cafetería del instituto. Tienen hambre después de clase. En la mesa hay bocadillos, fruta, agua y zumo. Sara quiere pedir un bocadillo de queso porque le gusta mucho. Pablo prefiere comprar una manzana y un zumo. Lucía pregunta: «¿Cuánto cuesta el bocadillo?». La mujer responde: «Cuesta tres euros». Lucía piensa que no es caro, pero solo tiene dos euros. Pregunta: «¿Cuál es la opción más barata?». La fruta cuesta un euro, así que pide una naranja y agua. Los amigos pagan y comen juntos. Después hablan del sábado. «¿Qué queréis hacer?», pregunta Pablo. A todos les gusta el cine, pero también quieren estar fuera. Al final deciden ir al parque por la mañana y al cine por la tarde.',
 sentences:['El viernes por la tarde, Lucía, Pablo y Sara van a la cafetería del instituto.','Tienen hambre después de clase.','En la mesa hay bocadillos, fruta, agua y zumo.','Sara quiere pedir un bocadillo de queso porque le gusta mucho.','Pablo prefiere comprar una manzana y un zumo.','Lucía pregunta: «¿Cuánto cuesta el bocadillo?».','La mujer responde: «Cuesta tres euros».','Lucía piensa que no es caro, pero solo tiene dos euros.','Pregunta: «¿Cuál es la opción más barata?».','La fruta cuesta un euro, así que pide una naranja y agua.','Los amigos pagan y comen juntos.','Después hablan del sábado.','«¿Qué queréis hacer?», pregunta Pablo.','A todos les gusta el cine, pero también quieren estar fuera.','Al final deciden ir al parque por la mañana y al cine por la tarde.'],
 sentenceTranslations:['On Friday afternoon, Lucía, Pablo, and Sara go to the school cafeteria.','They are hungry after class.','There are sandwiches, fruit, water, and juice on the table.','Sara wants to order a cheese sandwich because she likes it very much.','Pablo prefers to buy an apple and a juice.','Lucía asks, “How much does the sandwich cost?”','The woman answers, “It costs three euros.”','Lucía thinks it is not expensive, but she only has two euros.','She asks, “Which is the cheapest option?”','The fruit costs one euro, so she orders an orange and water.','The friends pay and eat together.','Afterwards, they talk about Saturday.','“What do you all want to do?” Pablo asks.','They all like the cinema, but they also want to be outside.','In the end, they decide to go to the park in the morning and the cinema in the afternoon.'],
 customVocabulary:vocab([['cafetería','cafeteria / café','noun'],['bocadillo','sandwich on a bread roll','noun'],['agua','water','noun'],['zumo','juice','noun'],['fruta','fruit','noun'],['precio','price','noun'],['euro','euro','noun'],['pedir','to order / ask for','verb'],['querer','to want','verb'],['gustar','to like','verb'],['comprar','to buy','verb'],['pagar','to pay','verb'],['cuánto','how much','question word'],['qué','what','question word'],['cuál','which / which one','question word'],['porque','because','connector'],['pero','but','connector'],['barato','cheap','adjective'],['caro','expensive','adjective'],['hambre','hunger','noun']]),
 comprehension:[{type:'Detail',prompt:'Why does Sara choose the cheese sandwich?',choices:['Because she likes it.','Because it is free.','Because Pablo orders it.'],answer:'Because she likes it.',feedback:'Sara wants it because she likes it very much.'},{type:'Number',prompt:'How much money does Lucía have?',choices:['One euro','Two euros','Three euros'],answer:'Two euros',feedback:'The sandwich costs three euros, but Lucía only has two.'},{type:'Plan',prompt:'What do the friends decide to do on Saturday?',choices:['Go to the park and the cinema','Study in the library','Eat at the cafeteria'],answer:'Go to the park and the cinema',feedback:'They choose the park in the morning and the cinema in the afternoon.'}],
 practice:[{text:['Sara ',' pedir un bocadillo.'],answer:'quiere',choices:['quiero','quiere','queréis']},{text:['¿',' cuesta la fruta?'],answer:'cuánto',choices:['qué','cuánto','cuál']},{text:['La fruta es más ','.'],answer:'barata',choices:['barata','cara','grande']}]
}
];
