const grammarWords={
 a:'to / at',al:'to the',de:'of / from',del:'of the / from the',en:'in / on',con:'with',sin:'without',por:'by / through / in',para:'for / in order to',hasta:'until / as far as',sobre:'on / about',entre:'between / among',dentro:'inside / within',junto:'next to / together',
 el:'the (masculine singular)',la:'the (feminine singular)',los:'the (masculine plural)',las:'the (feminine plural)',un:'a / one (masculine)',una:'a / one (feminine)',unos:'some (masculine)',unas:'some (feminine)',
 y:'and',o:'or',pero:'but',porque:'because',que:'that / which',cuando:'when',cómo:'how',cuándo:'when?',cuánto:'how much?',dónde:'where?',qué:'what?',cuál:'which?',si:'if',sí:'yes',no:'no / not',
 yo:'I',tú:'you',él:'he',ella:'she',ellos:'they',ellas:'they',nosotros:'we',vosotros:'you all',se:'himself / herself / themselves; reflexive marker',le:'to him / her',lo:'it / him',su:'his / her / their',sus:'his / her / their',mi:'my',tu:'your',
 este:'this',esta:'this',estos:'these',estas:'these',ese:'that',esa:'that',esos:'those',esas:'those',aquel:'that over there',aquella:'that over there',cada:'each / every',otro:'other / another',otra:'other / another',todo:'everything / all',todos:'everyone / all',todas:'all',cualquier:'any',ninguno:'neither / none',
 muy:'very',más:'more',también:'also',ya:'already / now',todavía:'still / yet',allí:'there',así:'so / like this',bien:'well',demasiado:'too / too much',poco:'little / not much',mucho:'a lot / much',muchos:'many',primero:'first',después:'afterwards',luego:'then / later',antes:'before',final:'end',pronto:'soon',rápidamente:'quickly',recientemente:'recently',últimamente:'lately',
 es:'is',son:'are',está:'is / is located',están:'are / are located',hay:'there is / there are',ha:'has',han:'have',has:'have / has',va:'goes / is going',van:'go / are going',puede:'can',pueden:'can',tiene:'has',tienen:'have',
 uno:'one',dos:'two',tres:'three',cuatro:'four',cinco:'five',seis:'six',siete:'seven',ocho:'eight',nueve:'nine',diez:'ten',veces:'times',día:'day',días:'days',noche:'night',tarde:'afternoon / late',mañana:'morning / tomorrow',semana:'week',mes:'month',año:'year',hora:'hour / time',sábado:'Saturday',lunes:'Monday'
};
const verbMeanings={
 abrir:'to open',aprender:'to learn',ayudar:'to help',bailar:'to dance',cambiar:'to change',caminar:'to walk',celebrar:'to celebrate',cenar:'to have dinner',cocinar:'to cook',combinar:'to match / combine',comer:'to eat',comprar:'to buy',conseguir:'to achieve / get',continuar:'to continue',colocar:'to place',cruzar:'to cross',deber:'to have to / should',decidir:'to decide',desayunar:'to have breakfast',descansar:'to rest',despertarse:'to wake up',dormir:'to sleep',ducharse:'to shower',elegir:'to choose',empezar:'to begin',enseñar:'to show / teach',entrenar:'to train',escribir:'to write',escuchar:'to listen',esperar:'to hope / wait',estar:'to be / be located',florecer:'to bloom',girar:'to turn',gustar:'to like',haber:'to have; auxiliary / there is',hablar:'to speak',hacer:'to do / make',ir:'to go',jugar:'to play',leer:'to read',levantarse:'to get up',limpiar:'to clean',llamar:'to call',llegar:'to arrive',meter:'to put inside',mirar:'to look / watch',necesitar:'to need',observar:'to observe',organizar:'to organise',parecer:'to seem',participar:'to take part',pensar:'to think',poner:'to put',preferir:'to prefer',preparar:'to prepare',preguntar:'to ask',probar:'to try',quedar:'to remain / arrange to meet',querer:'to want',recomendar:'to recommend',responder:'to answer',salir:'to leave / go out',señalar:'to point out',ser:'to be',servir:'to be suitable / serve',soler:'to usually do',terminar:'to finish',tocar:'to touch / play an instrument',trabajar:'to work',traer:'to bring',viajar:'to travel',visitar:'to visit',vestirse:'to get dressed',ver:'to see',volver:'to return'
};
const commonMeanings={
 ahora:'now',aire:'air',amigo:'friend',amigos:'friends',abuelos:'grandparents',actividades:'activities',ambiente:'atmosphere / environment',audios:'audio recordings',bilbao:'Bilbao',caliente:'hot',calle:'street',camino:'way / route',casa:'house / home',cena:'dinner',ciudad:'city',club:'club',clubes:'clubs',cocina:'kitchen',colores:'colours',cómodos:'comfortable',curso:'course',edificio:'building',eventos:'events',examen:'exam',excursión:'excursion',familia:'family',francés:'French',gratuita:'free of charge',grande:'large',guía:'guide',idiomas:'languages',instituto:'secondary school',ligera:'lightweight',libros:'books',lugar:'place',madre:'mother',mensajes:'messages',merienda:'afternoon snack',mochila:'backpack',montaña:'mountain',nuevo:'new',objeto:'object',paisaje:'landscape',pared:'wall',persona:'person',planes:'plans',plantas:'plants',práctica:'practical',preparado:'ready / prepared',preparadas:'ready / prepared',previsión:'forecast',prima:'female cousin',ropa:'clothes',salón:'living room',sillas:'chairs',sucio:'dirty',suficiente:'enough',tiempo:'time / weather',trabajo:'work / assignment',visitante:'visitor',vocabulario:'vocabulary'
};
export function getSpanishSupportInfo(word,verbData,sentenceTranslation=''){
 const key=word.toLocaleLowerCase('es');
 if(grammarWords[key])return {translation:grammarWords[key],role:'grammar word',example:sentenceTranslation||`See “${word}” in the reading sentence.`};
 if(verbData?.lemma){const meaning=verbMeanings[verbData.lemma];if(meaning)return {translation:meaning,role:'verb form',example:sentenceTranslation||`A form of ${verbData.lemma}.`};}
 if(commonMeanings[key])return {translation:commonMeanings[key],role:'word in context',example:sentenceTranslation||`See “${word}” in the reading sentence.`};
 if(/^[A-ZÁÉÍÓÚÜÑ]/.test(word))return {translation:word,role:'proper name',example:sentenceTranslation||`${word} is a name or place in this sentence.`};
 return {translation:sentenceTranslation?`Context: ${sentenceTranslation}`:'Meaning depends on this sentence.',role:'context word',example:sentenceTranslation||`See how “${word}” functions in the complete sentence.`};
}
