const vocab=items=>items.map(([word,translation,role='word in context'])=>({word,translation,role}));

export const spanishA1Batch2=[
{
 id:'es-a1-pilot-06',level:'A1',unit:6,title:'Una semana muy ocupada',topic:'Calendario y estudios',description:'Lucía organiza sus exámenes y tareas para una semana de instituto.',minutes:2,newWords:20,audio:'/audio/spanish/a1-pilot-06.mp3',
 grammarTargets:['Days and dates','Tener que + infinitive','Present-tense obligations','Cuándo for time questions'],
 targetVocabulary:['lunes','martes','miércoles','jueves','viernes','sábado','domingo','semana','mes','fecha','calendario','examen','tarea','asignatura','matemáticas','ciencias','necesitar','preparar','practicar','recordar'],recycledVocabulary:['clase','estudiar','hora','empezar','terminar','cuaderno','amigo'],
 passage:'El lunes, la profesora entrega el calendario del mes. Lucía mira todas las fechas porque tiene una semana muy ocupada. El martes tiene que entregar una tarea de ciencias. El miércoles necesita practicar inglés con Sara después de clase. El jueves hay un examen de matemáticas y Lucía quiere prepararlo bien. El viernes termina pronto su última asignatura. Pablo pregunta: «¿Qué hacemos el sábado?». Lucía responde que primero tiene que estudiar, pero después pueden quedar. El domingo quiere descansar con su familia. Para recordar cada actividad, escribe la fecha y la hora en su calendario. También prepara los libros y cuadernos que necesita. Al final, su semana parece más fácil porque todo tiene un día y un momento.',
 sentences:['El lunes, la profesora entrega el calendario del mes.','Lucía mira todas las fechas porque tiene una semana muy ocupada.','El martes tiene que entregar una tarea de ciencias.','El miércoles necesita practicar inglés con Sara después de clase.','El jueves hay un examen de matemáticas y Lucía quiere prepararlo bien.','El viernes termina pronto su última asignatura.','Pablo pregunta: «¿Qué hacemos el sábado?».','Lucía responde que primero tiene que estudiar, pero después pueden quedar.','El domingo quiere descansar con su familia.','Para recordar cada actividad, escribe la fecha y la hora en su calendario.','También prepara los libros y cuadernos que necesita.','Al final, su semana parece más fácil porque todo tiene un día y un momento.'],
 sentenceTranslations:['On Monday, the teacher hands out the calendar for the month.','Lucía looks at all the dates because she has a very busy week.','On Tuesday, she has to hand in a science assignment.','On Wednesday, she needs to practise English with Sara after class.','On Thursday, there is a mathematics exam and Lucía wants to prepare for it well.','On Friday, her final subject finishes early.','Pablo asks, “What are we doing on Saturday?”','Lucía answers that she first has to study, but afterwards they can meet.','On Sunday, she wants to rest with her family.','To remember each activity, she writes the date and time in her calendar.','She also prepares the books and notebooks that she needs.','In the end, her week seems easier because everything has a day and a time.'],
 customVocabulary:vocab([['lunes','Monday','day'],['martes','Tuesday','day'],['miércoles','Wednesday','day'],['jueves','Thursday','day'],['viernes','Friday','day'],['sábado','Saturday','day'],['domingo','Sunday','day'],['semana','week','noun'],['mes','month','noun'],['fecha','date','noun'],['calendario','calendar','noun'],['examen','exam','noun'],['tarea','assignment / task','noun'],['asignatura','school subject','noun'],['matemáticas','mathematics','noun'],['ciencias','science','noun'],['necesitar','to need','verb'],['preparar','to prepare','verb'],['practicar','to practise','verb'],['recordar','to remember','verb']]),
 comprehension:[{type:'Detail',prompt:'What does Lucía have on Thursday?',choices:['A mathematics exam','An English class','A family meal'],answer:'A mathematics exam',feedback:'The calendar shows a mathematics exam on Thursday.'},{type:'Sequence',prompt:'What must Lucía do before meeting her friends on Saturday?',choices:['Study','Visit the school','Prepare dinner'],answer:'Study',feedback:'She says she has to study first.'},{type:'Main idea',prompt:'Why does the week feel easier at the end?',choices:['Lucía organises everything in her calendar.','The teacher cancels the exam.','Pablo does all the homework.'],answer:'Lucía organises everything in her calendar.',feedback:'Writing each date and time makes the busy week manageable.'}],
 practice:[{text:['El martes tiene que entregar una ','.'],answer:'tarea',choices:['fecha','tarea','semana']},{text:['Lucía necesita ',' inglés.'],answer:'practicar',choices:['recordar','practicar','terminar']},{text:['El examen es el ','.'],answer:'jueves',choices:['mes','jueves','calendario']}]
},
{
 id:'es-a1-pilot-07',level:'A1',unit:7,title:'El club de los viernes',topic:'Aficiones y deporte',description:'Los amigos prueban actividades para elegir un club después de clase.',minutes:2,newWords:20,audio:'/audio/spanish/a1-pilot-07.mp3',
 grammarTargets:['Gustar + noun or infinitive','Poder + infinitive','Saber + infinitive','Expressing preferences'],
 targetVocabulary:['tiempo','deporte','fútbol','baloncesto','nadar','bailar','cantar','dibujar','tocar','escuchar','música','película','videojuego','bicicleta','equipo','favorito','divertido','aburrido','poder','saber'],recycledVocabulary:['viernes','amigo','instituto','querer','también','juntos'],
 passage:'Los viernes hay varios clubes en el instituto. Lucía quiere encontrar una actividad para su tiempo libre. A Pablo le gusta el deporte: juega al fútbol y al baloncesto en un equipo. Sara sabe nadar muy bien, pero no puede ir a la piscina los viernes. A Lucía le gusta escuchar música y tocar la guitarra. También sabe cantar un poco. Los tres visitan el club de arte, donde pueden dibujar, y el club de baile, donde aprenden a bailar. Pablo piensa que dibujar es aburrido, pero para Sara es divertido. Después ven una película corta sobre los clubes. Su actividad favorita es diferente para cada uno. Pablo elige fútbol, Sara elige baile y Lucía elige música. El sábado deciden montar en bicicleta juntos.',
 sentences:['Los viernes hay varios clubes en el instituto.','Lucía quiere encontrar una actividad para su tiempo libre.','A Pablo le gusta el deporte: juega al fútbol y al baloncesto en un equipo.','Sara sabe nadar muy bien, pero no puede ir a la piscina los viernes.','A Lucía le gusta escuchar música y tocar la guitarra.','También sabe cantar un poco.','Los tres visitan el club de arte, donde pueden dibujar, y el club de baile, donde aprenden a bailar.','Pablo piensa que dibujar es aburrido, pero para Sara es divertido.','Después ven una película corta sobre los clubes.','Su actividad favorita es diferente para cada uno.','Pablo elige fútbol, Sara elige baile y Lucía elige música.','El sábado deciden montar en bicicleta juntos.'],
 sentenceTranslations:['On Fridays, there are several clubs at the school.','Lucía wants to find an activity for her free time.','Pablo likes sport: he plays football and basketball on a team.','Sara can swim very well, but she cannot go to the pool on Fridays.','Lucía likes listening to music and playing the guitar.','She can also sing a little.','The three visit the art club, where they can draw, and the dance club, where they learn to dance.','Pablo thinks drawing is boring, but Sara thinks it is fun.','Afterwards, they watch a short film about the clubs.','Each person has a different favourite activity.','Pablo chooses football, Sara chooses dance, and Lucía chooses music.','On Saturday, they decide to ride bicycles together.'],
 customVocabulary:vocab([['tiempo','time / weather','noun'],['deporte','sport','noun'],['fútbol','football','noun'],['baloncesto','basketball','noun'],['nadar','to swim','verb'],['bailar','to dance','verb'],['cantar','to sing','verb'],['dibujar','to draw','verb'],['tocar','to play an instrument / touch','verb'],['escuchar','to listen','verb'],['música','music','noun'],['película','film','noun'],['videojuego','video game','noun'],['bicicleta','bicycle','noun'],['equipo','team','noun'],['favorito','favourite','adjective'],['divertido','fun','adjective'],['aburrido','boring','adjective'],['poder','can / to be able to','verb'],['saber','to know how to','verb']]),
 comprehension:[{type:'Detail',prompt:'Which activities does Lucía choose?',choices:['Music','Football','Dance'],answer:'Music',feedback:'Lucía likes listening to music, playing guitar, and singing.'},{type:'Meaning',prompt:'Why can Sara not swim on Fridays?',choices:['She cannot go to the pool.','She does not know how to swim.','She thinks swimming is boring.'],answer:'She cannot go to the pool.',feedback:'Sara knows how to swim, but cannot visit the pool on Fridays.'},{type:'Detail',prompt:'What do the friends plan for Saturday?',choices:['Ride bicycles','Watch a film','Play basketball'],answer:'Ride bicycles',feedback:'The final sentence gives their Saturday plan.'}],
 practice:[{text:['A Pablo le ',' el deporte.'],answer:'gusta',choices:['gustan','gusta','gusto']},{text:['Sara ',' nadar.'],answer:'sabe',choices:['puede a','sabe','saben']},{text:['En el club pueden ','.'],answer:'dibujar',choices:['dibujo','dibujar','dibujan']}]
},
{
 id:'es-a1-pilot-08',level:'A1',unit:8,title:'Ropa para un día diferente',topic:'Tiempo y ropa',description:'Un cambio de tiempo obliga a los amigos a elegir otra ropa.',minutes:2,newWords:20,audio:'/audio/spanish/a1-pilot-08.mp3',
 grammarTargets:['Weather expressions with hace, hay and está','Llevar and ponerse','Adjective agreement','Colours after nouns'],
 targetVocabulary:['clima','sol','lluvia','viento','calor','frío','nube','chaqueta','camiseta','pantalón','falda','zapato','vestido','llevar','poner','color','rojo','azul','verde','blanco'],recycledVocabulary:['mañana','tarde','sábado','querer','salir','mochila'],
 passage:'El sábado por la mañana hace sol y calor. Lucía quiere llevar una camiseta blanca, un pantalón azul y zapatos rojos. Sara lleva un vestido verde. Los amigos miran el clima antes de salir en bicicleta. En el mapa no hay lluvia, pero por la tarde aparecen muchas nubes. De pronto hace frío y hay mucho viento. Lucía tiene una chaqueta en la mochila y se la pone. Sara no lleva chaqueta y tiene frío. Pablo le presta una chaqueta de color azul. Poco después empieza la lluvia. Los tres vuelven a casa y cambian de plan. Preparan chocolate caliente y miran una película. Lucía aprende que el clima puede cambiar rápido y que es buena idea llevar ropa para el frío.',
 sentences:['El sábado por la mañana hace sol y calor.','Lucía quiere llevar una camiseta blanca, un pantalón azul y zapatos rojos.','Sara lleva un vestido verde.','Los amigos miran el clima antes de salir en bicicleta.','En el mapa no hay lluvia, pero por la tarde aparecen muchas nubes.','De pronto hace frío y hay mucho viento.','Lucía tiene una chaqueta en la mochila y se la pone.','Sara no lleva chaqueta y tiene frío.','Pablo le presta una chaqueta de color azul.','Poco después empieza la lluvia.','Los tres vuelven a casa y cambian de plan.','Preparan chocolate caliente y miran una película.','Lucía aprende que el clima puede cambiar rápido y que es buena idea llevar ropa para el frío.'],
 sentenceTranslations:['On Saturday morning, it is sunny and hot.','Lucía wants to wear a white T-shirt, blue trousers, and red shoes.','Sara is wearing a green dress.','The friends check the weather before going out on their bicycles.','The map shows no rain, but many clouds appear in the afternoon.','Suddenly, it is cold and very windy.','Lucía has a jacket in her backpack and puts it on.','Sara is not wearing a jacket and feels cold.','Pablo lends her a blue jacket.','Soon afterwards, the rain starts.','The three friends return home and change their plan.','They prepare hot chocolate and watch a film.','Lucía learns that the weather can change quickly and that taking clothes for cold weather is a good idea.'],
 customVocabulary:vocab([['clima','climate / weather','noun'],['sol','sun','noun'],['lluvia','rain','noun'],['viento','wind','noun'],['calor','heat','noun'],['frío','cold','noun / adjective'],['nube','cloud','noun'],['chaqueta','jacket','noun'],['camiseta','T-shirt','noun'],['pantalón','trousers','noun'],['falda','skirt','noun'],['zapato','shoe','noun'],['vestido','dress','noun'],['llevar','to wear / carry','verb'],['poner','to put','verb'],['color','colour','noun'],['rojo','red','adjective'],['azul','blue','adjective'],['verde','green','adjective'],['blanco','white','adjective']]),
 comprehension:[{type:'Weather',prompt:'How is the weather at the beginning?',choices:['Sunny and hot','Cold and rainy','Cloudy and windy'],answer:'Sunny and hot',feedback:'The first sentence says that it is sunny and hot.'},{type:'Detail',prompt:'Who does not have a jacket?',choices:['Sara','Lucía','Pablo'],answer:'Sara',feedback:'Lucía has one in her backpack, while Sara does not.'},{type:'Result',prompt:'What do they do after the rain starts?',choices:['Return home','Continue cycling','Go to school'],answer:'Return home',feedback:'They return home and watch a film.'}],
 practice:[{text:['Por la mañana hace ','.'],answer:'sol',choices:['sol','nube','viento']},{text:['Lucía lleva una camiseta ','.'],answer:'blanca',choices:['blanco','blanca','blancos']},{text:['Cuando hace frío, se ',' la chaqueta.'],answer:'pone',choices:['poner','pone','ponen']}]
},
{
 id:'es-a1-pilot-09',level:'A1',unit:9,title:'El camino a la estación',topic:'La ciudad y las direcciones',description:'Sara ayuda a una visitante a encontrar la estación del barrio.',minutes:2,newWords:20,audio:'/audio/spanish/a1-pilot-09.mp3',
 grammarTargets:['Informal affirmative commands','Direction expressions','Contractions al and del','Dónde and cómo questions'],
 targetVocabulary:['barrio','calle','plaza','tienda','supermercado','farmacia','estación','parada','banco','hospital','derecha','izquierda','recto','esquina','mapa','buscar','girar','cruzar','llegar','camino'],recycledVocabulary:['ciudad','cerca','lejos','delante','detrás','clase'],
 passage:'Sara camina por su barrio cuando una mujer le enseña un mapa. La mujer busca la estación de tren y pregunta por el camino. Sara explica: «Sigue recto por esta calle y gira a la derecha en la primera esquina». Primero tienen que cruzar una plaza. A la izquierda hay una farmacia y, delante, un supermercado grande. Después pasan junto a una tienda y un banco. La parada de autobús está cerca, pero la estación está un poco más lejos. «No gires junto al hospital», dice Sara. «Continúa recto hasta llegar a otra plaza. La estación está a la derecha». La mujer repite las indicaciones y da las gracias. Sara señala el camino correcto. Diez minutos después, la mujer llega a la estación sin problema.',
 sentences:['Sara camina por su barrio cuando una mujer le enseña un mapa.','La mujer busca la estación de tren y pregunta por el camino.','Sara explica: «Sigue recto por esta calle y gira a la derecha en la primera esquina».','Primero tienen que cruzar una plaza.','A la izquierda hay una farmacia y, delante, un supermercado grande.','Después pasan junto a una tienda y un banco.','La parada de autobús está cerca, pero la estación está un poco más lejos.','«No gires junto al hospital», dice Sara.','«Continúa recto hasta llegar a otra plaza. La estación está a la derecha».','La mujer repite las indicaciones y da las gracias.','Sara señala el camino correcto.','Diez minutos después, la mujer llega a la estación sin problema.'],
 sentenceTranslations:['Sara is walking through her neighbourhood when a woman shows her a map.','The woman is looking for the train station and asks for directions.','Sara explains, “Go straight along this street and turn right at the first corner.”','First, they have to cross a square.','There is a pharmacy on the left and a large supermarket ahead.','Then they pass a shop and a bank.','The bus stop is nearby, but the station is a little farther away.','“Do not turn by the hospital,” Sara says.','“Continue straight until you reach another square. The station is on the right.”','The woman repeats the directions and says thank you.','Sara points out the correct way.','Ten minutes later, the woman reaches the station without a problem.'],
 customVocabulary:vocab([['barrio','neighbourhood','noun'],['calle','street','noun'],['plaza','square','noun'],['tienda','shop','noun'],['supermercado','supermarket','noun'],['farmacia','pharmacy','noun'],['estación','station','noun'],['parada','stop','noun'],['banco','bank','noun'],['hospital','hospital','noun'],['derecha','right','direction'],['izquierda','left','direction'],['recto','straight ahead','direction'],['esquina','corner','noun'],['mapa','map','noun'],['buscar','to look for','verb'],['girar','to turn','verb'],['cruzar','to cross','verb'],['llegar','to arrive / reach','verb'],['camino','way / route','noun']]),
 comprehension:[{type:'Main idea',prompt:'What place is the woman looking for?',choices:['The train station','The hospital','The supermarket'],answer:'The train station',feedback:'She shows a map and asks for the way to the station.'},{type:'Direction',prompt:'Where should she turn at the first corner?',choices:['Right','Left','Back'],answer:'Right',feedback:'Sara says to turn right at the first corner.'},{type:'Result',prompt:'Does the woman find the station?',choices:['Yes, without a problem.','No, she returns to Sara.','No, she takes a bus.'],answer:'Yes, without a problem.',feedback:'She reaches it ten minutes later.'}],
 practice:[{text:['Sigue ',' por esta calle.'],answer:'recto',choices:['recto','esquina','mapa']},{text:['Gira a la ','.'],answer:'derecha',choices:['calle','derecha','parada']},{text:['La mujer busca la ','.'],answer:'estación',choices:['tienda','estación','farmacia']}]
},
{
 id:'es-a1-pilot-10',level:'A1',unit:10,title:'Planes para el fin de semana',topic:'Planes y transporte',description:'Lucía y sus amigos organizan una visita para el domingo.',minutes:2,newWords:20,audio:'/audio/spanish/a1-pilot-10.mp3',
 grammarTargets:['Ir a + infinitive for plans','Venir and quedar','Future time expressions','Quizás for possibility'],
 targetVocabulary:['fin','plan','visitar','viajar','salir','quedar','venir','invitar','traer','hacer','ver','jugar','paseo','museo','entrada','tren','autobús','posible','seguro','quizás'],recycledVocabulary:['sábado','domingo','amigo','fecha','hora','estación','parque','película'],
 passage:'Es viernes y los amigos hacen un plan para el fin de semana. Lucía quiere visitar un museo de ciencias el domingo. Pablo puede venir y va a invitar a su hermano. Sara no está segura porque quizás tiene un partido de baloncesto. Deciden quedar a las diez en la estación. Van a viajar en tren porque es rápido, aunque también hay un autobús. Cada entrada al museo cuesta cuatro euros. Lucía va a traer agua y Pablo va a preparar bocadillos. Después de ver el museo, quieren dar un paseo por el parque y jugar con una pelota. Sara mira su calendario y descubre que su partido es el sábado. «¡Sí, es posible! Voy a venir», dice. Todos están seguros de que van a pasar un buen día. Antes de salir, cada uno escribe la hora y el lugar.',
 sentences:['Es viernes y los amigos hacen un plan para el fin de semana.','Lucía quiere visitar un museo de ciencias el domingo.','Pablo puede venir y va a invitar a su hermano.','Sara no está segura porque quizás tiene un partido de baloncesto.','Deciden quedar a las diez en la estación.','Van a viajar en tren porque es rápido, aunque también hay un autobús.','Cada entrada al museo cuesta cuatro euros.','Lucía va a traer agua y Pablo va a preparar bocadillos.','Después de ver el museo, quieren dar un paseo por el parque y jugar con una pelota.','Sara mira su calendario y descubre que su partido es el sábado.','«¡Sí, es posible! Voy a venir», dice.','Todos están seguros de que van a pasar un buen día.','Antes de salir, cada uno escribe la hora y el lugar.'],
 sentenceTranslations:['It is Friday and the friends make a plan for the weekend.','Lucía wants to visit a science museum on Sunday.','Pablo can come and is going to invite his brother.','Sara is not sure because she may have a basketball match.','They decide to meet at ten at the station.','They are going to travel by train because it is fast, although there is also a bus.','Each museum ticket costs four euros.','Lucía is going to bring water and Pablo is going to prepare sandwiches.','After seeing the museum, they want to take a walk in the park and play with a ball.','Sara looks at her calendar and discovers that her match is on Saturday.','“Yes, it is possible! I am going to come,” she says.','They are all sure that they are going to have a good day.','Before leaving, each person writes down the time and place.'],
 customVocabulary:vocab([['fin','end; fin de semana means weekend','noun'],['plan','plan','noun'],['visitar','to visit','verb'],['viajar','to travel','verb'],['salir','to leave / go out','verb'],['quedar','to arrange to meet','verb'],['venir','to come','verb'],['invitar','to invite','verb'],['traer','to bring','verb'],['hacer','to do / make','verb'],['ver','to see','verb'],['jugar','to play','verb'],['paseo','walk / stroll','noun'],['museo','museum','noun'],['entrada','ticket / entrance','noun'],['tren','train','noun'],['autobús','bus','noun'],['posible','possible','adjective'],['seguro','sure / safe','adjective'],['quizás','perhaps / maybe','adverb']]),
 comprehension:[{type:'Plan',prompt:'Where do the friends plan to go?',choices:['A science museum','A football stadium','A shopping centre'],answer:'A science museum',feedback:'Lucía proposes visiting a science museum on Sunday.'},{type:'Transport',prompt:'How are they going to travel?',choices:['By train','By bicycle','On foot'],answer:'By train',feedback:'They choose the train because it is fast.'},{type:'Inference',prompt:'Why can Sara join them on Sunday?',choices:['Her match is on Saturday.','Her match is cancelled.','The museum is closed.'],answer:'Her match is on Saturday.',feedback:'Her calendar shows that the two activities are on different days.'}],
 practice:[{text:['Van a ',' un museo.'],answer:'visitar',choices:['visitan','visitar','visitáis']},{text:['Deciden ',' en la estación.'],answer:'quedar',choices:['quedar','venir','salir']},{text:['Lucía va a ',' agua.'],answer:'traer',choices:['ver','traer','jugar']}]
}
];
