const vocab=items=>items.map(([word,translation,role='word in context'])=>({word,translation,role}));
const makeReading=data=>({...data,level:'A1',minutes:3,newWords:20,targetVocabulary:data.words.map(x=>x[0]),customVocabulary:vocab(data.words)});

export const spanishA1VocabReadings=[
makeReading({
 id:'es-a1-vocab-11',unit:11,title:'Una mañana por el centro',topic:'Around Town',description:'Lucía ayuda a un visitante a orientarse por el centro de Madrid.',audio:'/audio/spanish/a1-vocab-11.mp3',grammarTargets:['Information Questions','Using “Hay” and Prepositions of Place','Demonstrative Adjectives'],
 words:[['ayuntamiento','town hall','noun'],['correos','post office','noun'],['panadería','bakery','noun'],['carnicería','butcher’s shop','noun'],['librería','bookshop','noun'],['quiosco','kiosk','noun'],['semáforo','traffic light','noun'],['puente','bridge','noun'],['acera','pavement','noun'],['avenida','avenue','noun'],['centro','town centre','noun'],['mapa','map','noun'],['esquina','corner','noun'],['derecha','right','direction'],['izquierda','left','direction'],['recto','straight ahead','direction'],['cerca','near','place word'],['lejos','far','place word'],['cruzar','to cross','verb'],['girar','to turn','verb']],
 passage:'Lucía está en el centro cuando un visitante abre un mapa y pregunta: «¿Dónde está el ayuntamiento?». Ella explica que está cerca, en esta avenida. Primero deben caminar recto por la acera hasta el semáforo y cruzar la calle. En la esquina hay un quiosco; allí tienen que girar a la derecha. Correos está a la izquierda, entre una panadería y una carnicería. La librería está un poco más lejos, junto al puente. El visitante señala un edificio y pregunta: «¿Es ese el ayuntamiento?». Lucía responde que sí y continúa su camino.',
 sentences:['Lucía está en el centro cuando un visitante abre un mapa y pregunta: «¿Dónde está el ayuntamiento?».','Ella explica que está cerca, en esta avenida.','Primero deben caminar recto por la acera hasta el semáforo y cruzar la calle.','En la esquina hay un quiosco; allí tienen que girar a la derecha.','Correos está a la izquierda, entre una panadería y una carnicería.','La librería está un poco más lejos, junto al puente.','El visitante señala un edificio y pregunta: «¿Es ese el ayuntamiento?».','Lucía responde que sí y continúa su camino.'],
 sentenceTranslations:['Lucía is in the town centre when a visitor opens a map and asks, “Where is the town hall?”','She explains that it is nearby, on this avenue.','First they must walk straight along the pavement to the traffic light and cross the street.','There is a kiosk on the corner; there they have to turn right.','The post office is on the left, between a bakery and a butcher’s shop.','The bookshop is a little farther away, next to the bridge.','The visitor points to a building and asks, “Is that the town hall?”','Lucía says yes and continues on her way.'],
 comprehension:[{type:'Place',prompt:'What place is the visitor looking for?',choices:['The town hall','The bookshop','The bridge'],answer:'The town hall',feedback:'He asks Lucía where the town hall is.'},{type:'Direction',prompt:'Where must they turn?',choices:['Right','Left','Back'],answer:'Right',feedback:'They turn right at the kiosk.'},{type:'Location',prompt:'What is between the bakery and the butcher’s shop?',choices:['The post office','The kiosk','The town hall'],answer:'The post office',feedback:'Correos is between the two shops.'}],
 practice:[{text:['¿Dónde está el ','.'],answer:'ayuntamiento',choices:['ayuntamiento','acera','esquina']},{text:['En la esquina ',' un quiosco.'],answer:'hay',choices:['es','hay','son']},{text:['Tienen que ',' a la derecha.'],answer:'girar',choices:['giran','girar','girando']}]
}),
makeReading({
 id:'es-a1-vocab-12',unit:12,title:'El festival del instituto',topic:'Events',description:'Los estudiantes preparan y celebran un festival de primavera.',audio:'/audio/spanish/a1-vocab-12.mp3',grammarTargets:['The Verb “Ser”','The Verb “Estar”','Prepositions of Time','Information Questions'],
 words:[['fiesta','party','noun'],['concierto','concert','noun'],['boda','wedding','noun'],['cumpleaños','birthday','noun'],['festival','festival','noun'],['entrada','ticket / entrance','noun'],['invitación','invitation','noun'],['invitado','guest','noun'],['escenario','stage','noun'],['música','music','noun'],['fecha','date','noun'],['hora','time / hour','noun'],['lugar','place','noun'],['empezar','to begin','verb'],['terminar','to finish','verb'],['celebrar','to celebrate','verb'],['bailar','to dance','verb'],['llegar','to arrive','verb'],['temprano','early','adverb'],['tarde','late / afternoon','adverb']],
 passage:'El festival del instituto es el sábado en el patio. Marta escribe la fecha, la hora y el lugar en cada invitación. La entrada es gratuita y cada invitado puede llegar temprano. El concierto va a empezar a las seis y el escenario ya está preparado. Hay música para bailar y una pequeña fiesta después del concierto. Sara quiere celebrar su cumpleaños allí, pero la boda de su prima es esa tarde. Pregunta: «¿Cuándo va a terminar el festival?». Marta responde que termina a las nueve, así que Sara no quiere llegar tarde a ninguno de los dos eventos.',
 sentences:['El festival del instituto es el sábado en el patio.','Marta escribe la fecha, la hora y el lugar en cada invitación.','La entrada es gratuita y cada invitado puede llegar temprano.','El concierto va a empezar a las seis y el escenario ya está preparado.','Hay música para bailar y una pequeña fiesta después del concierto.','Sara quiere celebrar su cumpleaños allí, pero la boda de su prima es esa tarde.','Pregunta: «¿Cuándo va a terminar el festival?».','Marta responde que termina a las nueve, así que Sara no quiere llegar tarde a ninguno de los dos eventos.'],
 sentenceTranslations:['The school festival is on Saturday in the playground.','Marta writes the date, time, and place on each invitation.','Entry is free, and every guest can arrive early.','The concert is going to start at six, and the stage is already ready.','There is music for dancing and a small party after the concert.','Sara wants to celebrate her birthday there, but her cousin’s wedding is that afternoon.','She asks, “When is the festival going to finish?”','Marta says it finishes at nine, so Sara does not want to arrive late for either event.'],
 comprehension:[{type:'Event',prompt:'Where is the festival?',choices:['In the school playground','In a theatre','At Sara’s house'],answer:'In the school playground',feedback:'The first sentence gives the event location.'},{type:'Time',prompt:'What time does the concert start?',choices:['Six','Seven','Nine'],answer:'Six',feedback:'The concert starts at six.'},{type:'Reason',prompt:'Why does Sara ask when the festival ends?',choices:['She also has a wedding.','She must buy a ticket.','She is performing on stage.'],answer:'She also has a wedding.',feedback:'Her cousin’s wedding is that afternoon.'}],
 practice:[{text:['El festival ',' en el patio.'],answer:'es',choices:['es','está','hay']},{text:['El escenario ya ',' preparado.'],answer:'está',choices:['es','son','está']},{text:['El concierto empieza ',' las seis.'],answer:'a',choices:['a','en','por']}]
}),
makeReading({
 id:'es-a1-vocab-13',unit:13,title:'¿Qué ropa llevo?',topic:'Colors and Clothes',description:'Lucía compara prendas y colores antes de una excursión.',audio:'/audio/spanish/a1-vocab-13.mp3',grammarTargets:['Adjectives and Adverbs','Demonstrative Adjectives','The Verb “Estar”'],
 words:[['camiseta','T-shirt','noun'],['camisa','shirt','noun'],['jersey','jumper','noun'],['chaqueta','jacket','noun'],['abrigo','coat','noun'],['pantalón','trousers','noun'],['falda','skirt','noun'],['vestido','dress','noun'],['zapatos','shoes','noun'],['botas','boots','noun'],['gorra','cap','noun'],['bufanda','scarf','noun'],['rojo','red','adjective'],['azul','blue','adjective'],['verde','green','adjective'],['amarillo','yellow','adjective'],['negro','black','adjective'],['blanco','white','adjective'],['gris','grey','adjective'],['morado','purple','adjective']],
 passage:'Lucía prepara la ropa para una excursión. Esta camiseta blanca y ese pantalón azul son cómodos. También prueba una camisa amarilla y un jersey verde, pero el jersey está sucio. Su chaqueta gris es ligera; aquel abrigo negro es demasiado caliente. Sara recomienda una falda morada o un vestido rojo, pero Lucía prefiere ropa práctica. Elige unas botas negras porque los zapatos blancos no sirven para la montaña. Mete una bufanda roja y una gorra amarilla en la mochila; le gustan el amarillo y el morado. Al final, todas las prendas están preparadas y los colores combinan bien.',
 sentences:['Lucía prepara la ropa para una excursión.','Esta camiseta blanca y ese pantalón azul son cómodos.','También prueba una camisa amarilla y un jersey verde, pero el jersey está sucio.','Su chaqueta gris es ligera; aquel abrigo negro es demasiado caliente.','Sara recomienda una falda morada o un vestido rojo, pero Lucía prefiere ropa práctica.','Elige unas botas negras porque los zapatos blancos no sirven para la montaña.','Mete una bufanda roja y una gorra amarilla en la mochila; le gustan el amarillo y el morado.','Al final, todas las prendas están preparadas y los colores combinan bien.'],
 sentenceTranslations:['Lucía prepares her clothes for an excursion.','This white T-shirt and those blue trousers are comfortable.','She also tries on a yellow shirt and a green jumper, but the jumper is dirty.','Her grey jacket is light; that black coat over there is too warm.','Sara recommends a purple skirt or a red dress, but Lucía prefers practical clothes.','She chooses black boots because white shoes are not suitable for the mountain.','She puts a red scarf and a yellow cap in her backpack; she likes yellow and purple.','In the end, all the clothes are ready and the colours go well together.'],
 comprehension:[{type:'Choice',prompt:'Why does Lucía choose boots?',choices:['They are suitable for the mountain.','They are yellow.','They are lighter than a T-shirt.'],answer:'They are suitable for the mountain.',feedback:'The white shoes are not suitable for the mountain.'},{type:'Detail',prompt:'Which item is dirty?',choices:['The green jumper','The grey jacket','The red scarf'],answer:'The green jumper',feedback:'The text says that the jumper is dirty.'},{type:'Main idea',prompt:'What is Lucía doing?',choices:['Preparing clothes for an excursion','Buying a wedding dress','Washing all her clothes'],answer:'Preparing clothes for an excursion',feedback:'She compares and packs practical clothes.'}],
 practice:[{text:['Esta camiseta es ','.'],answer:'blanca',choices:['blanco','blanca','blancos']},{text:['Esas botas son ','.'],answer:'negras',choices:['negra','negros','negras']},{text:['Lucía elige ',' pantalón azul.'],answer:'ese',choices:['esa','ese','estos']}]
}),
makeReading({
 id:'es-a1-vocab-14',unit:14,title:'Un día activo',topic:'Daily Activities',description:'Pablo explica las actividades que forman parte de su rutina.',audio:'/audio/spanish/a1-vocab-14.mp3',grammarTargets:['Present Simple','Prepositions of Time','Adjectives and Adverbs'],
 words:[['despertarse','to wake up','reflexive verb'],['levantarse','to get up','reflexive verb'],['ducharse','to shower','reflexive verb'],['vestirse','to get dressed','reflexive verb'],['desayunar','to have breakfast','verb'],['caminar','to walk','verb'],['estudiar','to study','verb'],['trabajar','to work','verb'],['comer','to eat / have lunch','verb'],['descansar','to rest','verb'],['leer','to read','verb'],['escribir','to write','verb'],['cocinar','to cook','verb'],['limpiar','to clean','verb'],['comprar','to buy','verb'],['llamar','to call','verb'],['escuchar','to listen','verb'],['volver','to return','verb'],['cenar','to have dinner','verb'],['dormir','to sleep','verb']],
 passage:'Pablo suele despertarse a las siete y levantarse enseguida. Después de ducharse y vestirse, va a desayunar con su familia. Empieza a caminar al instituto para estudiar por la mañana, y su madre empieza a trabajar. A las dos vuelve a casa para comer y descansar un poco. Por la tarde le gusta leer, escribir mensajes y escuchar música. Algunos días ayuda a cocinar y limpiar la cocina. Después sale a comprar pan o decide llamar a un amigo. Por la noche tiene que volver temprano, quiere cenar con su familia y se prepara para dormir.',
 sentences:['Pablo suele despertarse a las siete y levantarse enseguida.','Después de ducharse y vestirse, va a desayunar con su familia.','Empieza a caminar al instituto para estudiar por la mañana, y su madre empieza a trabajar.','A las dos vuelve a casa para comer y descansar un poco.','Por la tarde le gusta leer, escribir mensajes y escuchar música.','Algunos días ayuda a cocinar y limpiar la cocina.','Después sale a comprar pan o decide llamar a un amigo.','Por la noche tiene que volver temprano, quiere cenar con su familia y se prepara para dormir.'],
 sentenceTranslations:['Pablo usually wakes up at seven and gets up immediately.','After showering and getting dressed, he goes to have breakfast with his family.','He starts walking to school to study in the morning, and his mother starts work.','At two, he returns home to eat and rest for a while.','In the afternoon, he likes reading, writing messages, and listening to music.','On some days, he helps cook and clean the kitchen.','Afterwards, he goes out to buy bread or decides to call a friend.','At night, he has to return early, wants to have dinner with his family, and gets ready to sleep.'],
 comprehension:[{type:'Routine',prompt:'How does Pablo go to school?',choices:['He walks.','He takes a train.','He cycles.'],answer:'He walks.',feedback:'The text says that he walks to school.'},{type:'Time',prompt:'When does he read and write messages?',choices:['In the afternoon','At breakfast','During the night'],answer:'In the afternoon',feedback:'These activities happen in the afternoon.'},{type:'Home',prompt:'How does Pablo help at home?',choices:['He cooks and cleans.','He repairs the car.','He paints his room.'],answer:'He cooks and cleans.',feedback:'He helps in the kitchen on some days.'}],
 practice:[{text:['Pablo se ',' a las siete.'],answer:'despierta',choices:['despierto','despierta','despertáis']},{text:['Por la tarde ',' música.'],answer:'escucha',choices:['escucho','escucha','escuchan']},{text:['Por la noche Pablo ','.'],answer:'cena',choices:['cenar','cenáis','cena']}]
}),
makeReading({
 id:'es-a1-vocab-15',unit:15,title:'Ordenamos el salón',topic:'Household Objects',description:'Una familia reorganiza los objetos del salón y describe su posición.',audio:'/audio/spanish/a1-vocab-15.mp3',grammarTargets:['Using “Hay” and Prepositions of Place','Demonstrative Adjectives','The Verb “Estar”'],
 words:[['mesa','table','noun'],['silla','chair','noun'],['sofá','sofa','noun'],['lámpara','lamp','noun'],['alfombra','rug','noun'],['cortina','curtain','noun'],['estantería','shelving unit','noun'],['armario','cupboard','noun'],['cajón','drawer','noun'],['espejo','mirror','noun'],['reloj','clock','noun'],['televisión','television','noun'],['mando','remote control','noun'],['cojín','cushion','noun'],['jarrón','vase','noun'],['cuadro','picture','noun'],['puerta','door','noun'],['ventana','window','noun'],['techo','ceiling','noun'],['suelo','floor','noun']],
 passage:'En el salón hay un sofá junto a la ventana y una alfombra sobre el suelo. Delante del sofá están la mesa y dos sillas. Lucía coloca un cojín en el sofá y un jarrón encima de la mesa. La lámpara está cerca de la cortina, pero no toca el techo. En la pared hay un cuadro, un espejo y un reloj. La televisión está sobre un armario y el mando está dentro del primer cajón. Esa estantería queda al lado de la puerta. Cuando terminan, cada objeto está en su lugar y el salón parece más grande.',
 sentences:['En el salón hay un sofá junto a la ventana y una alfombra sobre el suelo.','Delante del sofá están la mesa y dos sillas.','Lucía coloca un cojín en el sofá y un jarrón encima de la mesa.','La lámpara está cerca de la cortina, pero no toca el techo.','En la pared hay un cuadro, un espejo y un reloj.','La televisión está sobre un armario y el mando está dentro del primer cajón.','Esa estantería queda al lado de la puerta.','Cuando terminan, cada objeto está en su lugar y el salón parece más grande.'],
 sentenceTranslations:['In the living room, there is a sofa next to the window and a rug on the floor.','The table and two chairs are in front of the sofa.','Lucía places a cushion on the sofa and a vase on the table.','The lamp is near the curtain, but it does not touch the ceiling.','There is a picture, a mirror, and a clock on the wall.','The television is on a cupboard, and the remote is inside the first drawer.','That shelving unit is next to the door.','When they finish, every object is in its place and the living room seems larger.'],
 comprehension:[{type:'Location',prompt:'Where is the rug?',choices:['On the floor','Inside the drawer','Above the television'],answer:'On the floor',feedback:'The rug is on the living-room floor.'},{type:'Detail',prompt:'What is inside the drawer?',choices:['The remote control','The clock','The cushion'],answer:'The remote control',feedback:'The remote is in the first drawer.'},{type:'Location',prompt:'What is next to the door?',choices:['The shelving unit','The sofa','The mirror'],answer:'The shelving unit',feedback:'The shelving unit is beside the door.'}],
 practice:[{text:['En el salón ',' un sofá.'],answer:'hay',choices:['hay','está','son']},{text:['El mando ',' en el cajón.'],answer:'está',choices:['hay','es','está']},{text:['¿Dónde está ',' estantería?'],answer:'esa',choices:['ese','esa','esos']}]
}),
makeReading({
 id:'es-a1-vocab-16',unit:16,title:'Una merienda para todos',topic:'Food and Containers',description:'Los amigos preparan cantidades y recipientes para una merienda.',audio:'/audio/spanish/a1-vocab-16.mp3',grammarTargets:['Countable and Uncountable Nouns','Information Questions','Present Simple'],
 words:[['pan','bread','noun'],['arroz','rice','noun'],['queso','cheese','noun'],['leche','milk','noun'],['agua','water','noun'],['zumo','juice','noun'],['manzana','apple','noun'],['tomate','tomato','noun'],['galleta','biscuit','noun'],['botella','bottle','container'],['vaso','glass','container'],['taza','cup','container'],['plato','plate','container'],['bol','bowl','container'],['caja','box','container'],['lata','tin / can','container'],['paquete','packet','container'],['kilo','kilogram','quantity'],['litro','litre','quantity'],['trozo','piece','quantity']],
 passage:'Los amigos preparan una merienda. Pablo compra un kilo de arroz y un paquete de pan. Sara trae una caja de galletas, una manzana y un tomate. Lucía pone un trozo de queso en cada plato. En la mesa hay una botella de agua, un litro de leche y una lata de zumo. Cada persona tiene un vaso para el agua y una taza para la leche. El arroz está en un bol grande. Pablo pregunta cuánto pan necesitan y Sara responde que un paquete es suficiente.',
 sentences:['Los amigos preparan una merienda.','Pablo compra un kilo de arroz y un paquete de pan.','Sara trae una caja de galletas, una manzana y un tomate.','Lucía pone un trozo de queso en cada plato.','En la mesa hay una botella de agua, un litro de leche y una lata de zumo.','Cada persona tiene un vaso para el agua y una taza para la leche.','El arroz está en un bol grande.','Pablo pregunta cuánto pan necesitan y Sara responde que un paquete es suficiente.'],
 sentenceTranslations:['The friends prepare an afternoon snack.','Pablo buys a kilogram of rice and a packet of bread.','Sara brings a box of biscuits, an apple, and a tomato.','Lucía puts a piece of cheese on each plate.','There is a bottle of water, a litre of milk, and a can of juice on the table.','Each person has a glass for water and a cup for milk.','The rice is in a large bowl.','Pablo asks how much bread they need, and Sara says that one packet is enough.'],
 comprehension:[{type:'Quantity',prompt:'How much rice does Pablo buy?',choices:['One kilogram','One litre','One piece'],answer:'One kilogram',feedback:'He buys a kilogram of rice.'},{type:'Container',prompt:'Where are the biscuits?',choices:['In a box','In a bottle','In a bowl'],answer:'In a box',feedback:'Sara brings a box of biscuits.'},{type:'Detail',prompt:'What is in the bowl?',choices:['Rice','Cheese','Juice'],answer:'Rice',feedback:'The rice is in a large bowl.'}],
 practice:[{text:['Un litro ',' leche.'],answer:'de',choices:['de','a','en']},{text:['Quiero dos ','.'],answer:'manzanas',choices:['agua','manzanas','arroz']},{text:['Hay una ',' de agua.'],answer:'botella',choices:['taza','plato','botella']}]
}),
makeReading({
 id:'es-a1-vocab-17',unit:17,title:'Cuatro estaciones en España',topic:'Seasons',description:'Sara compara el tiempo y sus planes durante las cuatro estaciones.',audio:'/audio/spanish/a1-vocab-17.mp3',grammarTargets:['Prepositions of Time','The Verb “Estar”','Adjectives and Adverbs'],
 words:[['primavera','spring','noun'],['verano','summer','noun'],['otoño','autumn','noun'],['invierno','winter','noun'],['estación','season','noun'],['enero','January','month'],['abril','April','month'],['julio','July','month'],['octubre','October','month'],['sol','sun','noun'],['lluvia','rain','noun'],['nieve','snow','noun'],['viento','wind','noun'],['calor','heat','noun'],['frío','cold','noun'],['templado','mild','adjective'],['seco','dry','adjective'],['húmedo','damp / humid','adjective'],['florecer','to bloom','verb'],['cambiar','to change','verb']],
 passage:'Cada estación tiene un tiempo diferente. En enero es invierno: hace frío, hay viento y a veces cae nieve. En abril llega la primavera, el aire está templado y las plantas empiezan a florecer. En julio es verano; hace calor, hay mucho sol y el paisaje está seco. En octubre empieza el otoño y vuelve la lluvia. Algunos días el ambiente está húmedo. Sara observa que el tiempo puede cambiar rápidamente en cualquier estación. Por eso mira la previsión antes de salir y elige ropa diferente para el frío, el calor, la lluvia o el viento.',
 sentences:['Cada estación tiene un tiempo diferente.','En enero es invierno: hace frío, hay viento y a veces cae nieve.','En abril llega la primavera, el aire está templado y las plantas empiezan a florecer.','En julio es verano; hace calor, hay mucho sol y el paisaje está seco.','En octubre empieza el otoño y vuelve la lluvia.','Algunos días el ambiente está húmedo.','Sara observa que el tiempo puede cambiar rápidamente en cualquier estación.','Por eso mira la previsión antes de salir y elige ropa diferente para el frío, el calor, la lluvia o el viento.'],
 sentenceTranslations:['Each season has different weather.','In January, it is winter: it is cold and windy, and sometimes it snows.','Spring arrives in April, the air is mild, and plants begin to bloom.','In July, it is summer; it is hot and sunny, and the landscape is dry.','Autumn begins in October, and the rain returns.','On some days, the air is damp.','Sara notices that the weather can change quickly in any season.','That is why she checks the forecast before going out and chooses different clothes for cold, heat, rain, or wind.'],
 comprehension:[{type:'Season',prompt:'When do plants begin to bloom?',choices:['In spring','In winter','In autumn'],answer:'In spring',feedback:'Plants begin to bloom when spring arrives.'},{type:'Weather',prompt:'How is the landscape in July?',choices:['Dry','Snowy','Damp'],answer:'Dry',feedback:'Summer is hot and the landscape is dry.'},{type:'Habit',prompt:'What does Sara do before going out?',choices:['She checks the forecast.','She buys a calendar.','She opens the window.'],answer:'She checks the forecast.',feedback:'She checks because the weather can change.'}],
 practice:[{text:['En enero hace ','.'],answer:'frío',choices:['frío','seco','sol']},{text:['Las plantas empiezan a ','.'],answer:'florecer',choices:['florecen','florecer','floreciendo']},{text:['En verano el paisaje ',' seco.'],answer:'está',choices:['hay','es','está']}]
}),
makeReading({
 id:'es-a1-vocab-18',unit:18,title:'El sábado de los clubes',topic:'Leisure Activities',description:'Los amigos eligen deportes, aficiones y actividades para el sábado.',audio:'/audio/spanish/a1-vocab-18.mp3',grammarTargets:['Modals and Infinitives','Present Simple','Adjectives and Adverbs'],
 words:[['fútbol','football','noun'],['baloncesto','basketball','noun'],['tenis','tennis','noun'],['natación','swimming','noun'],['ciclismo','cycling','noun'],['senderismo','hiking','noun'],['baile','dance','noun'],['pintura','painting','noun'],['fotografía','photography','noun'],['lectura','reading','noun'],['música','music','noun'],['cine','cinema','noun'],['teatro','theatre','noun'],['ajedrez','chess','noun'],['videojuego','video game','noun'],['entrenar','to train','verb'],['practicar','to practise','verb'],['aprender','to learn','verb'],['participar','to take part','verb'],['elegir','to choose','verb']],
 passage:'El sábado hay muchos clubes. Pablo quiere practicar fútbol y baloncesto, pero también puede entrenar tenis. Sara prefiere la natación, el ciclismo y el senderismo. Lucía quiere aprender baile, pintura y fotografía. En la biblioteca hay un club de lectura y otro de ajedrez. Por la tarde pueden escuchar música, ir al cine o ver teatro. También hay un torneo de videojuego. Los amigos tienen que elegir dos actividades y quieren participar juntos en una. Al final eligen fotografía por la mañana y senderismo por la tarde.',
 sentences:['El sábado hay muchos clubes.','Pablo quiere practicar fútbol y baloncesto, pero también puede entrenar tenis.','Sara prefiere la natación, el ciclismo y el senderismo.','Lucía quiere aprender baile, pintura y fotografía.','En la biblioteca hay un club de lectura y otro de ajedrez.','Por la tarde pueden escuchar música, ir al cine o ver teatro.','También hay un torneo de videojuego.','Los amigos tienen que elegir dos actividades y quieren participar juntos en una.','Al final eligen fotografía por la mañana y senderismo por la tarde.'],
 sentenceTranslations:['There are many clubs on Saturday.','Pablo wants to practise football and basketball, but he can also train in tennis.','Sara prefers swimming, cycling, and hiking.','Lucía wants to learn dance, painting, and photography.','There is a reading club and a chess club in the library.','In the afternoon, they can listen to music, go to the cinema, or see theatre.','There is also a video-game tournament.','The friends have to choose two activities and want to take part in one together.','In the end, they choose photography in the morning and hiking in the afternoon.'],
 comprehension:[{type:'Preference',prompt:'Which activities does Sara prefer?',choices:['Swimming, cycling, and hiking','Dance, painting, and photography','Football, basketball, and tennis'],answer:'Swimming, cycling, and hiking',feedback:'The third sentence lists Sara’s preferences.'},{type:'Place',prompt:'Which clubs are in the library?',choices:['Reading and chess','Cinema and theatre','Cycling and hiking'],answer:'Reading and chess',feedback:'Both are available in the library.'},{type:'Plan',prompt:'What do they choose for the morning?',choices:['Photography','Hiking','Football'],answer:'Photography',feedback:'They choose photography in the morning.'}],
 practice:[{text:['Pablo quiere ',' fútbol.'],answer:'practicar',choices:['practica','practicar','practicando']},{text:['Lucía puede ',' baile.'],answer:'aprender',choices:['aprende','aprender','aprendiendo']},{text:['Tienen que ',' dos actividades.'],answer:'elegir',choices:['eligen','elegir','elegís']}]
}),
makeReading({
 id:'es-a1-vocab-19',unit:19,title:'Todo lo que hemos hecho',topic:'Past Time Phrases',description:'Lucía utiliza expresiones temporales para hablar de experiencias recientes.',audio:'/audio/spanish/a1-vocab-19.mp3',grammarTargets:['Past Tense','Prepositions of Time','Present Perfect in Spain Spanish'],
 words:[['hoy','today','time expression'],['esta mañana','this morning','time expression'],['esta tarde','this afternoon','time expression'],['esta noche','tonight','time expression'],['esta semana','this week','time expression'],['este mes','this month','time expression'],['este año','this year','time expression'],['ya','already','adverb'],['todavía no','not yet','time expression'],['alguna vez','ever','time expression'],['nunca','never','adverb'],['recientemente','recently','adverb'],['hace poco','a short time ago','time expression'],['últimamente','lately','adverb'],['primero','first','sequencing word'],['después','afterwards','sequencing word'],['luego','then','sequencing word'],['antes','before','sequencing word'],['al final','in the end','sequencing phrase'],['por fin','at last','sequencing phrase']],
 passage:'Hoy Lucía ha pensado en todo lo que ha hecho recientemente. Esta mañana primero ha terminado un trabajo y después ha llamado a Sara. Luego han hablado de esta semana. Esta tarde Lucía ya ha visitado la biblioteca, pero todavía no ha preparado la cena para esta noche. Hace poco ha empezado un curso nuevo y últimamente ha estudiado mucho. Este mes ha leído dos libros; este año ha viajado tres veces. Antes ha leído una guía, pero nunca ha preguntado: «¿Has estado alguna vez en Bilbao?». Al final Sara ha respondido y por fin han organizado un viaje.',
 sentences:['Hoy Lucía ha pensado en todo lo que ha hecho recientemente.','Esta mañana primero ha terminado un trabajo y después ha llamado a Sara.','Luego han hablado de esta semana.','Esta tarde Lucía ya ha visitado la biblioteca, pero todavía no ha preparado la cena para esta noche.','Hace poco ha empezado un curso nuevo y últimamente ha estudiado mucho.','Este mes ha leído dos libros; este año ha viajado tres veces.','Antes ha leído una guía, pero nunca ha preguntado: «¿Has estado alguna vez en Bilbao?».','Al final Sara ha respondido y por fin han organizado un viaje.'],
 sentenceTranslations:['Today, Lucía has thought about everything she has done recently.','This morning, she first finished an assignment and afterwards called Sara.','Then they talked about this week.','This afternoon, Lucía has already visited the library, but she has not yet prepared dinner for tonight.','She started a new course recently and has studied a lot lately.','This month, she has read two books; this year, she has travelled three times.','Before, she has read a guide, but she has never asked, “Have you ever been to Bilbao?”','In the end, Sara replied, and at last they organised a trip.'],
 comprehension:[{type:'Sequence',prompt:'What did Lucía do first this morning?',choices:['She finished an assignment.','She visited Bilbao.','She prepared dinner.'],answer:'She finished an assignment.',feedback:'Primero introduces the first completed action.'},{type:'Progress',prompt:'What has Lucía not done yet?',choices:['Prepared dinner','Visited the library','Called Sara'],answer:'Prepared dinner',feedback:'Todavía no marks the unfinished action.'},{type:'Result',prompt:'What have the friends finally organised?',choices:['A trip','A course','A dinner'],answer:'A trip',feedback:'Por fin introduces the final result.'}],
 practice:[{text:['Hoy Lucía ',' estudiado.'],answer:'ha',choices:['ha','han','he']},{text:['Todavía no hemos ',' la cena.'],answer:'preparado',choices:['preparar','preparamos','preparado']},{text:['¿Has viajado ',' vez?'],answer:'alguna',choices:['alguna','nunca','antes de']}]
}),
makeReading({
 id:'es-a1-vocab-20',unit:20,title:'Los planes de Lucía',topic:'Future Time Expressions',description:'Lucía organiza planes próximos y sueños para el futuro.',audio:'/audio/spanish/a1-vocab-20.mp3',grammarTargets:['Future Expressions','Ir a + Infinitive','Prepositions of Time'],
 words:[['mañana','tomorrow','time expression'],['pasado mañana','the day after tomorrow','time expression'],['esta noche','tonight','time expression'],['este fin de semana','this weekend','time expression'],['el lunes próximo','next Monday','time expression'],['la semana que viene','next week','time expression'],['el mes que viene','next month','time expression'],['el año que viene','next year','time expression'],['pronto','soon','adverb'],['más tarde','later','time expression'],['luego','then / later','sequencing word'],['después','afterwards','sequencing word'],['dentro de una hora','in an hour','time expression'],['dentro de dos días','in two days','time expression'],['en verano','in summer','time expression'],['en Navidad','at Christmas','time expression'],['algún día','someday','time expression'],['próximamente','soon / shortly','adverb'],['por la mañana','in the morning','time expression'],['por la tarde','in the afternoon','time expression']],
 passage:'Esta noche Lucía va a escribir todos sus planes. Dentro de una hora va a llamar a Pablo. Mañana por la mañana van a estudiar y más tarde van a jugar al tenis. Pasado mañana, dentro de dos días, van a visitar a Sara por la tarde. Este fin de semana van a preparar una excursión. El lunes próximo empieza un curso y la semana que viene tiene un examen. El mes que viene Lucía va a viajar; el año que viene quiere estudiar en otra ciudad. En verano va a trabajar y en Navidad va a visitar a sus abuelos. Próximamente quiere aprender francés: primero va a estudiar vocabulario, luego va a escuchar audios y después va a practicar. Algún día va a hablar tres idiomas; espera conseguirlo pronto.',
 sentences:['Esta noche Lucía va a escribir todos sus planes.','Dentro de una hora va a llamar a Pablo.','Mañana por la mañana van a estudiar y más tarde van a jugar al tenis.','Pasado mañana, dentro de dos días, van a visitar a Sara por la tarde.','Este fin de semana van a preparar una excursión.','El lunes próximo empieza un curso y la semana que viene tiene un examen.','El mes que viene Lucía va a viajar; el año que viene quiere estudiar en otra ciudad.','En verano va a trabajar y en Navidad va a visitar a sus abuelos.','Próximamente quiere aprender francés: primero va a estudiar vocabulario, luego va a escuchar audios y después va a practicar.','Algún día va a hablar tres idiomas; espera conseguirlo pronto.'],
 sentenceTranslations:['Tonight, Lucía is going to write down all her plans.','In an hour, she is going to call Pablo.','Tomorrow morning, they are going to study, and later they are going to play tennis.','The day after tomorrow, in two days, they are going to visit Sara in the afternoon.','This weekend, they are going to prepare an excursion.','A course starts next Monday, and she has an exam next week.','Lucía is going to travel next month; next year, she wants to study in another city.','She is going to work in summer and is going to visit her grandparents at Christmas.','Soon, she wants to learn French: first she is going to study vocabulary, then listen to audio, and afterwards practise.','Someday she is going to speak three languages; she hopes to achieve it soon.'],
 comprehension:[{type:'Immediate plan',prompt:'What will Lucía do in an hour?',choices:['Call Pablo','Take an exam','Visit her grandparents'],answer:'Call Pablo',feedback:'Dentro de una hora introduces the phone call.'},{type:'Next week',prompt:'What will happen next week?',choices:['There will be an exam.','Lucía will visit her grandparents.','She will work in summer.'],answer:'There will be an exam.',feedback:'The text gives an exam as next week’s event.'},{type:'Long-term goal',prompt:'What does Lucía hope to do someday?',choices:['Speak three languages','Open a school','Move tomorrow'],answer:'Speak three languages',feedback:'Algún día introduces her long-term goal.'}],
 practice:[{text:['Mañana voy a ','.'],answer:'estudiar',choices:['estudio','estudiar','estudiando']},{text:['El mes que viene Lucía ',' a viajar.'],answer:'va',choices:['voy','va','van']},{text:['Dentro ',' dos días visitarán a Sara.'],answer:'de',choices:['a','por','de']}]
})
];
